### ISSUE TITLE
Drop product doubles

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#105]
Оригинал задачи от Сеошников:
http://client.webit.ru/?act=8#que_id=66602

----

Полные дубли
http://www.stroyprombeton.ru/gbi/products/12237/
http://www.StroyPromBeton.ru/gbi/products/9026/

http://www.stroyprombeton.ru/gbi/products/12240/
http://www.stroyprombeton.ru/gbi/products/12228/

http://www.stroyprombeton.ru/gbi/products/13902/
http://www.stroyprombeton.ru/gbi/products/13903/

http://www.stroyprombeton.ru/gbi/products/4056/
http://www.stroyprombeton.ru/gbi/products/4046/

Чтобы найти все, нужно сделать выгрузку из базы данных и найти дубли по h1, харакетристикам, цене. От дублей нужно избавиться.

**Comment by dveselov** [comment]
Сделал выборку одинаковых продуктов таким запросом:
```python
from django.db.models import Count

dups = (
    Product
    .objects
    .values('page__h1', 'mark', 'specification', 'category')
    .annotate(Count('id'))
    .order_by()
    .filter(id__count__gt=1)
)
```
Получившийся список дублей удалял так:
```python
for dup in dups:
    """
    dup = {
        'page__h1': 'Панель стеновая',
        'mark': '2ПС84-1ш',
        'specification': 'Серия 3.902.1-12, выпуск 1',
        'category': 184,
        'id__count': 2,
    }
    """
    del dup['id_count']
    Product.objects.filter(**dup).first().delete()
```
Нашлось около 20-ти дублей.

**Comment by duker33** [comment]
@dveselov , го добавим этот код командой в django-команду.
Впереди много работы по контенту. Он скорее всего не раз пригодится в разных вариациях с разными полями
