### ISSUE TITLE
Fix microdata on CategoryPage and ProductPage

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#106]
> "Напомню, что я обеспокоен нашей микроразметкой

Действительно, на данный момент имеются ошибке в разметке:

1) Используется микроформат hCard. Яндекс ставит обязательным условием наличие свойств fn и org, т.е. название организации. Поэтому нужно добавить:

```
<span class="fn org">СТК-Промбетон</span>
```

2) Используется разметка Open Graph. Яндекс ставит обязательным условием наличие метатега og:image. Поэтому нужно добавить:

```
<meta property="og:image" content="урл_картинки_на_странице">
```

Эта картинка будет показываться в превью, которое формируется при публикации ссылки на страницу в социальных сетях и других интернет-сервисах. Например в карточках товара нужно размечать этим тегом фото товара. На остальных страницах можно разметить, например, логотип компании.

3) Фото в карточках размечены свойством itemprop="image", без привязки к кому-либо типу разметки Schema.org. Поэтому стоит добавить разметку Product. Пример разметки для карточки http://www.stroyprombeton.ru/gbi/products/4175/:
```
<div itemscope itemtype="http://schema.org/Product">

<h1 itemprop="name">Плита дорожная железобетонная ПДН</h1>

<span itemprop="description"><p>Организуем доставку Плита дорожная железобетонная марки ПДН по всей России автомобильным, железнодорожным, водным транспортом. Можно воспользоваться самовывозом.</p><br><p>У нас нет фиксированной цены доставки, поэтому звоните менеджеру, чтобы ее узнать. Менеджер поможет выбрать способ доставки, рассчитает стоимость и назовет срок.</p><br><p>На каждое изделие выдается паспорт в соответствии с ГОСТ 13015-2012.</p></span>

<img class="img-centered img-responsive" src="/static/images/common/image-thumb.3cd446960424.png" alt="Фотография Плита дорожная железобетонная" itemprop="image">

<div itemprop="offers" itemscope itemtype="http://schema.org/Offer"> 

<span itemprop="price">17600</span>

<span itemprop="priceCurrency" content="RUB">руб</span>

</div>

</div>
```
Т.е. данными тегами нужно разметить уже имеющиеся элементы в коде: h1, шаблонный текст, цену

В категориях, в качестве картинки, можно использовать логотип, но лучше нижнюю картинку из текста. Соответственно во все категории нужно добавить такую картинку. В http://client.webit.ru/?act=8&showall=1#que_id=66598 я указывал это в рекомендациях.

**Comment by dveselov** [comment]
С микроданными на странице продуктов (третий пункт) всё ОК (можно проверить [здесь](https://webmaster.yandex.com/tools/microtest/)): ![](https://i.imgur.com/qpnI6Ni.png)
Остальное пофикшено в https://github.com/fidals/stroyprombeton/pull/108

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#121](https://github.com/fidals/stroyprombeton/issues/121) is solved here.
