### ISSUE TITLE
Включить gzip сжатие

### ISSUE THREAD

**Issue by dveselov** [fidals/stroyprombeton#109]
Сервис Google PageSpeed [рекомендует](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.stroyprombeton.ru%2F&tab=desktop) нам включить сжатие для изображений и другой статики

Related to #107

**Comment by themygit** [comment]
@duker33 бизнес ругался на пережатые изображения. На которых появляется "грязь" вокруг изделий. http://prntscr.com/gyiy3u
Можно с этим что-то сделать ?

**Comment by dveselov** [comment]
Могу вернуть оригинальные картинки.

**Comment by duker33** [comment]
> Могу вернуть оригинальные картинки.

@dveselov , тогда верни плз :)

**Comment by dveselov** [comment]
@duker33 а где их взять? :)
В мастере сейчас вот эти картинки, на которые указал @themygit, тоже с артифактами: https://github.com/fidals/stroyprombeton/blob/master/front/images/catalog-new-jersey.png (и последнее изменение год назад)

**Comment by themygit** [comment]
Должны быть в трелло

**Comment by duker33** [comment]
> Должны быть в трелло

@themygit , линк на Трелло с картинками плз :)

**Comment by dveselov** [comment]
в трелло есть [такие картинки](https://trello.com/c/QOYH4nCd/237-stb-%D0%BC%D0%B5%D0%BD%D1%8F%D0%B9-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8-%D0%B2-%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3%D0%B5), но они с страницы каталога (не главной страницы)

**Comment by themygit** [comment]
@dveselov пойду спрошу у бизнеса
