### ISSUE TITLE
Оптимизировать изображения

### ISSUE THREAD

**Issue by dveselov** [fidals/stroyprombeton#115]
Сервис Google PageSpeed рекомендует оптимизировать изображения, чтобы уменьшить размер страницы  
Сделать это нативными инструментами (чистый питон и какой-нибудь `PIL`) - трудно (готовых библиотек не существует?)
Но есть, например, [вот такая библиотека](https://pypi.python.org/pypi/picopt/), которая приносит с собой `optipng`, `jpegtran` и другие бинарники для оптимизации изображений.  
Еще нужно определиться, как поступать с изображениями -  оптимизировать их при сохранении (перезаписывать метод `save` или получать сигнал `post_save`) или периодически запускать команду с оптимизацией (так же, как мы обновляем прайслисты в se)  

Related to #107

**Comment by dveselov** [comment]
Вручную прошелся по медиафайлам используя `jpegtran` - PageSpeed-рейтинг поднялся на несколько пунктов, но пока не дотягивает до зеленого.

**Comment by duker33** [comment]
хмм, а может есть какие-нить сервисы, в которые можно ходить с изображениями для оптимизации?

**Comment by dveselov** [comment]
Таких много, из лучших - [tinypng.com](https://tinypng.com/) и [tinyjpg.com](https://tinyjpg.com/) с бесплатной квотой в 500 изображений/месяц.
Их анализатор компрессии, кстати, говорит что изображения уже более-менее оптимизированы: https://tinyjpg.com/analyzer#stroyprombeton.ru

**Comment by duker33** [comment]
> Их анализатор компрессии, кстати, говорит что изображения уже более-менее оптимизированы: 
ну по линку он говорит о 20% размера. Имхо это немало.
С другой стороны, фактор довольно сомнительный. Наверное он не стоит стольких страданий.
Го просто закроем эту задачу. У нас есть фичи поприбыльнее
