### ISSUE TITLE
Makefile:15-15: run backup before deploy

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#118]
Зависит от #130 

-------

The puzzle `117-cb0461b4` (from #117) in [`docker/Makefile`](https://github.com/fidals/stroyprombeton/blob/master/docker/Makefile) (lines 15-15) has to be resolved: "run backup before deploy"

The puzzle was created by Dima Veselov on 11-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by dveselov** [comment]
Зависит от https://github.com/fidals/stroyprombeton/pull/130
