### ISSUE TITLE
Пофиксь pdd форматирование. 

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#136]
https://github.com/fidals/stroyprombeton/blob/d089199d6111f824575ac6fd55a8ca94bbafed4d/docker/Makefile#L31

**Comment by dveselov** [comment]
Пофиксили здесь https://github.com/fidals/stroyprombeton/pull/135/files#diff-11ee4a521ee318acb249451574624884 (нужно было добавить пустую строку между обычным комментарием PDD-задачей)
