### ISSUE TITLE
Autobuild local env as on SE

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#142]
В ~https://github.com/fidals/shopelectro/issues/176~ https://github.com/fidals/shopelectro/issues/269 всё реализовали.

Повтори это на Бетоне или убедись, что это реализовано

**Comment by artemiy312** [comment]
It is more relevant version of SE deploy system https://github.com/fidals/shopelectro/issues/269

**Comment by duker33** [comment]
@artemiy312 , i'm going to implement this task together with #167 
Hope you didn't start it

**Comment by duker33** [comment]
task was too big for one hour. I decided not to split it for subtasks not to break system

**Comment by duker33** [comment]
waiting for review

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#205](https://github.com/fidals/stroyprombeton/issues/205), [#206](https://github.com/fidals/stroyprombeton/issues/206), [#207](https://github.com/fidals/stroyprombeton/issues/207), [#208](https://github.com/fidals/stroyprombeton/issues/208), [#209](https://github.com/fidals/stroyprombeton/issues/209), [#210](https://github.com/fidals/stroyprombeton/issues/210), [#211](https://github.com/fidals/stroyprombeton/issues/211) are still not solved.

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#205](https://github.com/fidals/stroyprombeton/issues/205), [#206](https://github.com/fidals/stroyprombeton/issues/206), [#209](https://github.com/fidals/stroyprombeton/issues/209), [#210](https://github.com/fidals/stroyprombeton/issues/210), [#211](https://github.com/fidals/stroyprombeton/issues/211) are still not solved; solved: [#207](https://github.com/fidals/stroyprombeton/issues/207), [#208](https://github.com/fidals/stroyprombeton/issues/208).

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#205](https://github.com/fidals/stroyprombeton/issues/205), [#206](https://github.com/fidals/stroyprombeton/issues/206), [#211](https://github.com/fidals/stroyprombeton/issues/211) are still not solved; solved: [#207](https://github.com/fidals/stroyprombeton/issues/207), [#208](https://github.com/fidals/stroyprombeton/issues/208), [#209](https://github.com/fidals/stroyprombeton/issues/209), [#210](https://github.com/fidals/stroyprombeton/issues/210).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#205](https://github.com/fidals/stroyprombeton/issues/205), [#211](https://github.com/fidals/stroyprombeton/issues/211) are still not solved; solved: [#206](https://github.com/fidals/stroyprombeton/issues/206), [#207](https://github.com/fidals/stroyprombeton/issues/207), [#208](https://github.com/fidals/stroyprombeton/issues/208), [#209](https://github.com/fidals/stroyprombeton/issues/209), [#210](https://github.com/fidals/stroyprombeton/issues/210).

**Comment by 0pdd** [comment]
@duker33 6 puzzles [#205](https://github.com/fidals/stroyprombeton/issues/205), [#211](https://github.com/fidals/stroyprombeton/issues/211), [#409](https://github.com/fidals/stroyprombeton/issues/409), [#410](https://github.com/fidals/stroyprombeton/issues/410), [#411](https://github.com/fidals/stroyprombeton/issues/411), [#412](https://github.com/fidals/stroyprombeton/issues/412) are still not solved; solved: [#206](https://github.com/fidals/stroyprombeton/issues/206), [#207](https://github.com/fidals/stroyprombeton/issues/207), [#208](https://github.com/fidals/stroyprombeton/issues/208), [#209](https://github.com/fidals/stroyprombeton/issues/209), [#210](https://github.com/fidals/stroyprombeton/issues/210).

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#205](https://github.com/fidals/stroyprombeton/issues/205), [#409](https://github.com/fidals/stroyprombeton/issues/409), [#410](https://github.com/fidals/stroyprombeton/issues/410), [#411](https://github.com/fidals/stroyprombeton/issues/411), [#412](https://github.com/fidals/stroyprombeton/issues/412) are still not solved; solved: [#206](https://github.com/fidals/stroyprombeton/issues/206), [#207](https://github.com/fidals/stroyprombeton/issues/207), [#208](https://github.com/fidals/stroyprombeton/issues/208), [#209](https://github.com/fidals/stroyprombeton/issues/209), [#210](https://github.com/fidals/stroyprombeton/issues/210), [#211](https://github.com/fidals/stroyprombeton/issues/211).
