### ISSUE TITLE
Напиши инструкцию по разворачиванию проекта на локали

### ISSUE THREAD

**Issue by dveselov** [fidals/stroyprombeton#150]
Аналогично https://github.com/fidals/shopelectro/issues/229
Очень нужно, т.к. после последних [изменений в docker-compose конфиге](https://github.com/fidals/stroyprombeton/pull/139), пришлось искать, что там вообще произошло и править свой локальный конфиг.

**Comment by duker33** [comment]
@dveselov , инструкция не спасёт от несвежего локального `.env`.
Мы можем сделать баш/питон скрипт, который при старте `dc up -d se-python` будет проверять все ли ключи из .env.dist есть в локальном .env и писать варнинги.
Го сделаем?

**Comment by dveselov** [comment]
@duker33 если я правильно помню, `docker-compose` выдаёт варнинги, если переменные, которые используются в его конфиге отсутствуют в `.env`. При этом, он всё равно запустит контейнеры, присвоив необъявленным переменным пустую строку.
Идея с скриптом хорошая, но наверное лучше было бы полностью валидировать `.env` по схеме и не давать запускать контейнеры.

**Comment by duker33** [comment]
> Идея с скриптом хорошая, но наверное лучше было бы полностью валидировать .env по схеме и не давать запускать контейнеры.

@dveselov , принято

**Comment by 0pdd** [comment]
@dveselov the only puzzle [#159](https://github.com/fidals/stroyprombeton/issues/159) is solved here.
