### ISSUE TITLE
Category ChoiceField autocomplete

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#151]
[trello origin](https://trello.com/c/9h2YIHUj/296-stb-category-choisefield-autocomplete)

В Админке добавляем автокомплит при создании категорий http://prntscr.com/eepm4q

Речь идёт о Category EditPage. Вот пример:
http://www.stroyprombeton.ru/admin/stroyprombeton/categorypage/15312/change/

Если нажмёшь на поле "Родитель", узнаешь наш скрин. Сейчас там неудобненько, т.к. ~200 категорий нужно скроллить, чтобы найти нужную для выбора

**Comment by dveselov** [comment]
@artemiy312 выкатил на прод вместе с #156

**Comment by artemiy312** [comment]
@dveselov спасибо!
