### ISSUE TITLE
docker-compose.yml:42-43: Validate if `.env` is full Is...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#159]
The puzzle `150-9a03496d` from #150 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/36b7fd02c5e8f88bb94f3871a331c9aac8aa4bfe/docker/docker-compose.yml#L42-L43

The puzzle was created by duker33 on 26-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
будет хорошо пореюзать эту таску для SE тоже.
Возможно, коду от неё самое место в репе Рефарма

**Comment by duker33** [comment]
fixed it already
