### ISSUE TITLE
base.py:231-233: List mail recipients in config Remove...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#163]
The puzzle `160-956c9262` from #160 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/3001a148570702c50ef212b4eb3deaf5de98c62a/stroyprombeton/settings/base.py#L231-L233

The puzzle was created by duker33 on 13-Jan-18. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by chelovek-18** [comment]
Просьба уточнить, правильно ли я понял задачу:

Нужно из .env.dist и base.py удалить EMAIL_RECIPIENT и SHOP_EMAIL а добавить (туда же?) - список EMAIL_RECIPIENTS - я так полагаю через запятую.

**Comment by duker33** [comment]
@chelovek-18 , да, всё верно.
Сейчас проблема в том, что у нас разные переменные с разными названиями, но одной семантикой:
`SHOP_EMAIL, EMAIL_RECIPIENT`. Мы их объединим в одну переменную с чистой семантикой
