### ISSUE TITLE
STB ошибка при открытии новости

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#168]
http://www.stroyprombeton.ru/page/news/bloki-niu-dzhersi-dlia-iakhtennogo-mosta/ при открытии белый экран

**Comment by chelovek-18** [comment]
@duker33 
В самом тексте статьи не закрыт тег style:

`<style>


.col-xs-12 {
	margin-bottom: 25px;
}

.image1 {
    float: left;
    display: inline-block;
    width: 45%;
    margin-right: 35px;
}

.image2 {
    float: left;
    width: 45%;
}

li {
	list-style-type: none;
}

.sign {
	font-size: 13px;
}


<style>`

Т.е. в конце <style> надо исправить на </style>. Не могу испрвить т.к. нет доступа к тексту.
