### ISSUE TITLE
STB поиск в table editor

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#169]
Поиск в table editor не ищет по марке изделия.  Нужно добавить.

**Comment by chelovek-18** [comment]
Можно уточнить, где именно не ищет?.. А то у меня вот:
![search1](https://user-images.githubusercontent.com/6870960/38839513-a8fb0eb6-41e3-11e8-87a1-b83eb176d24b.png)
![search2](https://user-images.githubusercontent.com/6870960/38839533-ba1ae25c-41e3-11e8-914c-53ffb75a5d36.png)

**Comment by duker33** [comment]
@themygit , закрываю

**Comment by themygit** [comment]
Я писал про тейбл эдитор.  а не про поиск на сайте

**Comment by duker33** [comment]
`2 hours` taught much codes, wrote tests&realization in the same task

**Comment by duker33** [comment]
@chelovek-18 fights with tests
