### ISSUE TITLE
Admin page create 404 bug

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#172]
Из чата:
слушай, я тут новость хотел добавить на промбетон. нажал сохранить и продолжить - получил это http://www.stroyprombeton.ru/admin/stroyprombeton/newsforadmin/29899/change/

**Comment by duker33** [comment]
stb сыпется на `make dev`.
Посмотрю на следующей неделе

**Comment by artemiy312** [comment]
@duker33 #173 пофиксит его

**Comment by duker33** [comment]
wait for CI resurrect

**Comment by duker33** [comment]
now depends from #344

**Comment by duker33** [comment]
can't reproduce on local env

**Comment by duker33** [comment]
we should just select parent page "news" in edit page form
![image](https://user-images.githubusercontent.com/3526796/43991774-52263a30-9d7c-11e8-8513-ab75bd7ec1b0.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#297](https://github.com/fidals/stroyprombeton/issues/297) is still not solved.
