### ISSUE TITLE
Проверка refarm-site совместно с stroyprombeton

### ISSUE THREAD

**Issue by chelovek-18** [fidals/stroyprombeton#183]
Когда я вношу изменения в stroyprombeton я могу проверить работоспособность перезапустив его; есть ли возможность проверить в рабочем режиме refarm-site, т.к. бывают задачи когда требуется добавление взаимодействующего кода сразу и в stroyprombeton и refarm-site, что исключает возможность немедленной проверки?

**Comment by artemiy312** [comment]
@chelovek-18 Тебе нужно проделать несколько действий:
1. склонировать refarm-site
2. примонтировать refarm-site в докер контейнер с исходниками зависимостей

Пример: проект лежит в /Workflow/shopelectro, а refarm-site в /Workflow/refarm-site.
Обновляем переменную [REFARM_SRC](https://github.com/fidals/stroyprombeton/blob/master/docker/.env.dist#L13)=/Workflow/refarm-site, чтобы использовать ее в [docker-compose.yml](https://github.com/fidals/stroyprombeton/blob/master/docker/docker-compose.yml#L12) (в этом примере монтируется приложение search)
