### ISSUE TITLE
Tags feature

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#187]
It's already implemented on SE.

Some UI decision is needed here

**Comment by duker33** [comment]
i'll fix https://github.com/fidals/shopelectro/issues/522 for the first.
Otherwise we'll double this bug to STB

**Comment by duker33** [comment]
bloked by https://github.com/fidals/refarm-site/issues/168

**Comment by duker33** [comment]
resolve some problems directly in this task

**Comment by duker33** [comment]
finished moving context scope. I'll continue with astronomical hours while i'll get prototype on stb prod.
Then i'll close this task and move on with pdd subtasks

**Comment by 0pdd** [comment]
@duker33 8 puzzles [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#315](https://github.com/fidals/stroyprombeton/issues/315), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320) are still not solved.

**Comment by 0pdd** [comment]
@duker33 8 puzzles [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335) are still not solved; solved: [#315](https://github.com/fidals/stroyprombeton/issues/315).

**Comment by 0pdd** [comment]
@duker33 13 puzzles [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335), [#340](https://github.com/fidals/stroyprombeton/issues/340), [#341](https://github.com/fidals/stroyprombeton/issues/341), [#342](https://github.com/fidals/stroyprombeton/issues/342), [#343](https://github.com/fidals/stroyprombeton/issues/343), [#344](https://github.com/fidals/stroyprombeton/issues/344) are still not solved; solved: [#315](https://github.com/fidals/stroyprombeton/issues/315).

**Comment by 0pdd** [comment]
@duker33 9 puzzles [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335), [#340](https://github.com/fidals/stroyprombeton/issues/340) are still not solved; solved: [#315](https://github.com/fidals/stroyprombeton/issues/315), [#341](https://github.com/fidals/stroyprombeton/issues/341), [#342](https://github.com/fidals/stroyprombeton/issues/342), [#343](https://github.com/fidals/stroyprombeton/issues/343), [#344](https://github.com/fidals/stroyprombeton/issues/344).

**Comment by 0pdd** [comment]
@duker33 8 puzzles [#314](https://github.com/fidals/stroyprombeton/issues/314), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335), [#340](https://github.com/fidals/stroyprombeton/issues/340) are still not solved; solved: [#313](https://github.com/fidals/stroyprombeton/issues/313), [#315](https://github.com/fidals/stroyprombeton/issues/315), [#341](https://github.com/fidals/stroyprombeton/issues/341), [#342](https://github.com/fidals/stroyprombeton/issues/342), [#343](https://github.com/fidals/stroyprombeton/issues/343), [#344](https://github.com/fidals/stroyprombeton/issues/344).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335), [#340](https://github.com/fidals/stroyprombeton/issues/340) are still not solved; solved: [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#315](https://github.com/fidals/stroyprombeton/issues/315), [#341](https://github.com/fidals/stroyprombeton/issues/341), [#342](https://github.com/fidals/stroyprombeton/issues/342), [#343](https://github.com/fidals/stroyprombeton/issues/343), [#344](https://github.com/fidals/stroyprombeton/issues/344).

**Comment by 0pdd** [comment]
@duker33 6 puzzles [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335), [#405](https://github.com/fidals/stroyprombeton/issues/405), [#406](https://github.com/fidals/stroyprombeton/issues/406) are still not solved; solved: [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#315](https://github.com/fidals/stroyprombeton/issues/315), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#340](https://github.com/fidals/stroyprombeton/issues/340), [#341](https://github.com/fidals/stroyprombeton/issues/341), [#342](https://github.com/fidals/stroyprombeton/issues/342), [#343](https://github.com/fidals/stroyprombeton/issues/343), [#344](https://github.com/fidals/stroyprombeton/issues/344).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335), [#405](https://github.com/fidals/stroyprombeton/issues/405), [#406](https://github.com/fidals/stroyprombeton/issues/406), [#468](https://github.com/fidals/stroyprombeton/issues/468) are still not solved; solved: [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#315](https://github.com/fidals/stroyprombeton/issues/315), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#340](https://github.com/fidals/stroyprombeton/issues/340), [#341](https://github.com/fidals/stroyprombeton/issues/341), [#342](https://github.com/fidals/stroyprombeton/issues/342), [#343](https://github.com/fidals/stroyprombeton/issues/343), [#344](https://github.com/fidals/stroyprombeton/issues/344).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#318](https://github.com/fidals/stroyprombeton/issues/318), [#319](https://github.com/fidals/stroyprombeton/issues/319), [#320](https://github.com/fidals/stroyprombeton/issues/320), [#335](https://github.com/fidals/stroyprombeton/issues/335), [#405](https://github.com/fidals/stroyprombeton/issues/405), [#406](https://github.com/fidals/stroyprombeton/issues/406), [#526](https://github.com/fidals/stroyprombeton/issues/526) are still not solved; solved: [#313](https://github.com/fidals/stroyprombeton/issues/313), [#314](https://github.com/fidals/stroyprombeton/issues/314), [#315](https://github.com/fidals/stroyprombeton/issues/315), [#316](https://github.com/fidals/stroyprombeton/issues/316), [#317](https://github.com/fidals/stroyprombeton/issues/317), [#340](https://github.com/fidals/stroyprombeton/issues/340), [#341](https://github.com/fidals/stroyprombeton/issues/341), [#342](https://github.com/fidals/stroyprombeton/issues/342), [#343](https://github.com/fidals/stroyprombeton/issues/343), [#344](https://github.com/fidals/stroyprombeton/issues/344), [#468](https://github.com/fidals/stroyprombeton/issues/468).
