### ISSUE TITLE
Makefile:67-68: Resurrect backup system. Right now it's...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#205]
The puzzle `142-0169d767` from #142 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/89cc959e8665f358e437b7d2b0b35a76d2e4f1d4/docker/Makefile#L67-L68

The puzzle was created by Artemiy on 15-Jun-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
we should modify backup in this way:
- drop static folder backup
- do incremental backup over media folder
- do sql, but not binary backup over db

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#409](https://github.com/fidals/stroyprombeton/issues/409), [#410](https://github.com/fidals/stroyprombeton/issues/410), [#411](https://github.com/fidals/stroyprombeton/issues/411), [#412](https://github.com/fidals/stroyprombeton/issues/412) are still not solved.
