### ISSUE TITLE
CI docker-build does not work

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#213]
https://ci.fidals.com/fidals/stroyprombeton/76/11

**Comment by duker33** [comment]
@artemiy312 , i think, this task is not about 1 hour. It's about two additional symbols in dockerfile

![image](https://user-images.githubusercontent.com/3526796/41518860-5536b1a2-72cd-11e8-94d5-23f8dd0c53c4.png)
e

**Comment by artemiy312** [comment]
@duker33 Yes, it is. When I discovered the problem, I did not know how long it would take.
