### ISSUE TITLE
Правь микроразметку

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#216]
1) hCard. Валидатор гугла жалуется на неразмеченную картинку http://prntscr.com/jv7ygy. Для этого добавьте class="photo" http://prntscr.com/jv7yyw 
- и видимо вгрузить png лого вместо вектора

2) В разделах, например http://www.stroyprombeton.ru/gbi/categories/457/ заголовок h1 размечен тегом itemprop="name", который не относится ни к одному типу микроразметки. Отсюда ошибка http://prntscr.com/jv8aq3. Нужно убрать лишнее свойство http://prntscr.com/jv8b0x

**Comment by duker33** [comment]
i'll implement it on SE too
