### ISSUE TITLE
Some tests regression

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#218]
Tests always fails

https://ci.fidals.com/fidals/stroyprombeton/94/8
https://ci.fidals.com/fidals/stroyprombeton/87/8

**Comment by duker33** [comment]
depends on #203

**Comment by duker33** [comment]
I'll try to fix the problem with #203 task's pr https://github.com/fidals/stroyprombeton/pull/220

Increased timeout for the first and commented some degraded tests

**Comment by 0pdd** [comment]
@duker33 the puzzle [#224](https://github.com/fidals/stroyprombeton/issues/224) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#224](https://github.com/fidals/stroyprombeton/issues/224) is solved here.
