### ISSUE TITLE
tests_views.py:471-472: Resurrect test_price_list test....

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#224]
The puzzle `218-2254cca6` from #218 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/e83753c565194eec6aa6e7527ea62265b07b154a/stroyprombeton/tests/tests_views.py#L471-L472

The puzzle was created by duker33 on 20-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
unassign this task. 5 days left

**Comment by duker33** [comment]
downgrade every test resurrection to `15 min`. Because they should be resurrected fastly in a bunch

**Comment by artemiy312** [comment]
Closes in favor of #292

**Comment by duker33** [comment]
test resurrected, you solved this problem
