### ISSUE TITLE
Resurrect stage

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#232]
Resurrect stage.stroyprombeton.ru
It should use it's own DB.
Needed for STB DB + multitags massive refactoring

**Comment by duker33** [comment]
it's required only for `Tags` feature

**Comment by 0pdd** [comment]
@duker33 the puzzle [#321](https://github.com/fidals/stroyprombeton/issues/321) is still not solved.

**Comment by duker33** [comment]
resolved with https://github.com/fidals/stroyprombeton/pull/311

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#321](https://github.com/fidals/stroyprombeton/issues/321) is solved here.
