### ISSUE TITLE
tests_selenium_admin.py:568: Fill two Product's mark...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#235]
The puzzle `215-3296d73b` from #215 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/5293a811909dd27eff07c45597b0c9cce11444fc/stroyprombeton/tests/tests_selenium_admin.py#L568-L568

The puzzle was created by chelovek-18 on 05-Jul-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
created another pdd task intead of it
