### ISSUE TITLE
Selenium timeout secrets aren't visible to app. se2

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#263]

**Comment by duker33** [comment]
drone can't see env values from pull_request.
Tried this:

```
drone secret add \
  --image fidals/stb:dev \
  --event pull_request \
  --event push \
  --event tag \
  --repository fidals/stroyprombeton \
  --name SELENIUM_TIMEOUT_SECONDS \
  --value 120

drone secret add \
  --image fidals/stb:dev \
  --event pull_request \
  --event push \
  --event tag \
  --repository fidals/stroyprombeton \
  --name SELENIUM_WAIT_SECONDS \
  --value 120
```

But, it's not work. Refuse this task

**Comment by duker33** [comment]
@artemiy312 , saw related PRs. Unfortunately we have some problems with drone secrets visibility.

Use drone cli to share visibility for drone secrets: http://readme.drone.io/cli/drone-secret-add/
But it did not help for me last time i tried it. We had some additional problems

**Comment by artemiy312** [comment]
@duker33 Yes, it was, but now I deal with the issue

**Comment by duker33** [comment]
@artemiy312 , this issue happens sometimes because of serv or smth.
I usually just relaunch pipeline in this cases

**Comment by duker33** [comment]
@artemiy312 , what was the solution. You just added secrets with drone cli?
