### ISSUE TITLE
base.py:147-155: Cleanup front/build usage. Now different...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#266]
The puzzle `257-f16bf56d` from #257 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/be5be8ac12b41f83f4672d2411ec285e98ffdff3/stroyprombeton/settings/base.py#L147-L155

The puzzle was created by duker33 on 20-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
@duker33 
>app dev maps static files to ./build dir with volumes

mm, it seems it is not. We map only `./../:$SRC_DIR`

**Comment by duker33** [comment]
> mm, it seems it is not. We map only ./../:$SRC_DIR

@artemiy312 , y, seems app dev inherits `front/build` from this mapping.
But it does not matter. I'll refactor all names

**Comment by 0pdd** [comment]
@0pdd the puzzle [#274](https://github.com/fidals/stroyprombeton/issues/274) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#274](https://github.com/fidals/stroyprombeton/issues/274) is solved here.
