### ISSUE TITLE
Drone-build fails with 137 code

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#267]
https://ci.fidals.com/fidals/stroyprombeton/277/11

Maybe it's because memory limit:
https://docs.docker.com/config/containers/resource_constraints/

**Comment by duker33** [comment]
maybe it was because of no disk space on serv. I'll try again

**Comment by duker33** [comment]
seems we still have problems with it.
Not only in push builds, but in pull_request ones too
https://ci.fidals.com/fidals/stroyprombeton/324/9

**Comment by duker33** [comment]
it's os problem. So, i increase it's solving time dramatically.
@artemiy312 , if you want, you can take this issue from me

**Comment by artemiy312** [comment]
@duker33 Y, I would like to take it

**Comment by artemiy312** [comment]
Done
We [catch](https://github.com/drone/drone-exec/blob/c9e59c4f91e93cc1540e86a02451ea224b47de69/main.go#L201) timeout that stopped a build in such  non-verbose way. I already have increased timeout value

**Comment by artemiy312** [comment]
Appended 15 mins due to #283

**Comment by duker33** [comment]
> Appended 15 mins due to #283

@artemiy312 , parallel deps execution is not useful, because i'll rm this deps at #280 and #284 

You pr #283 resolves #206 task, so, you'll receive pay for it
