### ISSUE TITLE
Improve drone with volumes and builds

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#268]
Repeat this changes:
- https://github.com/fidals/shopelectro/pull/428
- https://github.com/fidals/shopelectro/pull/437
- se#352's [subtask](https://github.com/fidals/shopelectro/pull/437/files#diff-3216dfff0ed3e301453e6799e8c367e2R9)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#279](https://github.com/fidals/stroyprombeton/issues/279) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#279](https://github.com/fidals/stroyprombeton/issues/279) is solved here.
