### ISSUE TITLE
Integrate js ecommerce tracking

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#269]
We already [made](https://github.com/fidals/shopelectro/pull/416) it for SE.
For detail see a parent [issue](https://github.com/fidals/refarm-site/issues/129)

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#273](https://github.com/fidals/stroyprombeton/issues/273) is still not solved.

**Comment by 0pdd** [comment]
@artemiy312 the only puzzle [#273](https://github.com/fidals/stroyprombeton/issues/273) is solved here.
