### ISSUE TITLE
test_db.py:62-66: Save fixture images to `media` folder....

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#296]
The puzzle `289-cdb3e4e2` from #289 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/42087613ef354de3c34ed0027fb38dd764af03f1/stroyprombeton/management/commands/test_db.py#L62-L66

The puzzle was created by duker33 on 13-Aug-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
the problem is in timestamp.
Image creation copies image file to the new path, but filename contains timestamp.
That's why on dev machines media folder becomes more stale, then fixtures db

**Comment by 0pdd** [comment]
@0pdd the puzzle [#384](https://github.com/fidals/stroyprombeton/issues/384) is still not solved.
