### ISSUE TITLE
Fix jsecommerce as in SE

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#303]
We should implement it after we test jsecommerce in SE.

An issue with a detail: https://github.com/fidals/shopelectro/issues/504
Reproduce these PRs: https://github.com/fidals/shopelectro/pull/531, https://github.com/fidals/shopelectro/pull/532, https://github.com/fidals/shopelectro/pull/520, https://github.com/fidals/shopelectro/issues/589

**Comment by artemiy312** [comment]
It seems all right, so I start

**Comment by duker33** [comment]
@artemiy312 , i remind you for this issue

**Comment by 0pdd** [comment]
@artemiy312 2 puzzles [#365](https://github.com/fidals/stroyprombeton/issues/365), [#366](https://github.com/fidals/stroyprombeton/issues/366) are still not solved.
