### ISSUE TITLE
Dockerfile.dev:1-4: Upgrade python to 3.7 3.7 version...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#309]
The puzzle `570-b7fb1b1b` from #570 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/a15c6d4aa8effe59ad505fcd1b1aaf3d169a0c7b/docker/images/python/Dockerfile.dev#L1-L4

The puzzle was created by Artemiy on 14-Sep-18. 

Estimate: 120 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
this issue blocks several code cleanups. We are waiting dataclass for example

**Comment by duker33** [comment]
CI catches segfault because of this string at Product_.setUp method:
`self.response = self.client.get('/gbi/products/{}/'.format(product.id))`

**Comment by duker33** [comment]
i localized one of tests.
Now we should localize other tests, that was broken by migrating to py3.7
I'll do it at the same task
