### ISSUE TITLE
category.html:44-45: Fix tags markup Now added only html...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#313]
The puzzle `187-5270833f` from #187 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/4f1b5b3c8da15d2450bfa77e9c229b713213c546/templates/catalog/category.html#L44-L45

The puzzle was created by duker33 on 24-Sep-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
i need to do this task fastly. So, by my own

**Comment by duker33** [comment]
![image](https://user-images.githubusercontent.com/3526796/48611869-4fec7f00-e998-11e8-8747-3b1f3fe33030.png)

resolved with direct push to master
