### ISSUE TITLE
tests_selenium_admin.py:294-295: Stabilize TableEditor...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#316]
The puzzle `187-1700602f` from #187 has to be resolved:

https://github.com/fidals/stroyprombeton/blob/4f1b5b3c8da15d2450bfa77e9c229b713213c546/stroyprombeton/tests/tests_selenium_admin.py#L294-L295

The puzzle was created by duker33 on 24-Sep-18. 

Estimate: 120 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
it seems we meant Table Editor class itself there.
So, i'll implement it as separated task
