### ISSUE TITLE
Reuse context to enable Tags feature

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#328]
Refresh STB new refarm-sites's context to enable tags feature

**Comment by 0pdd** [comment]
@duker33 the puzzle [#336](https://github.com/fidals/stroyprombeton/issues/336) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#336](https://github.com/fidals/stroyprombeton/issues/336) is solved here.
