### ISSUE TITLE
Create Product options arch

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#330]
from #326 

Every product can have several values of the same tag.
For example "Mark" tag for product.
See mockup for a live example
https://app.moqups.com/elena.lyapina.firefly@gmail.com/qqMWIFbla7/view

**Comment by artemiy312** [comment]
@duker33 What do exactly we should implement here? currently nothing inhibits us to assign several tags of a same group to a product

**Comment by duker33** [comment]
@artemiy312 , just pinned link on mockup to task body.
We should be able to attach several values of the same tags to one product.

In mockup's example we should pin several values of the one "Mark" tag
![image](https://user-images.githubusercontent.com/3526796/47960475-54b34980-e00e-11e8-8537-d136e892da90.png)

**Comment by duker33** [comment]
i realized, that task is not about Tags, but about new Products schema.
I'll propose new schema with comments
