### ISSUE TITLE
tests_views.py:662: Render options on product page

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#335]
The puzzle `315-9094883c` from #315 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/ffac41ab668aeb261949dc20355c27740c169204/stroyprombeton/tests/tests_views.py#L662-L662

The puzzle was created by duker33 on 14-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
Mockup is here
https://app.moqups.com/elena.lyapina.firefly@gmail.com/qqMWIFbla7/view

**Comment by duker33** [comment]
markup is not my specialization, so increased rate.
Now table looks like this
![image](https://user-images.githubusercontent.com/3526796/53343852-5f2d8200-3922-11e9-92d6-c8f8c820735f.png)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#468](https://github.com/fidals/stroyprombeton/issues/468) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#526](https://github.com/fidals/stroyprombeton/issues/526) is still not solved; solved: [#468](https://github.com/fidals/stroyprombeton/issues/468).
