### ISSUE TITLE
Implement "flush" button for tags filter

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#339]
![image](https://user-images.githubusercontent.com/3526796/48658146-b4b5e100-ea4d-11e8-8ba1-6023f685b34b.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#352](https://github.com/fidals/stroyprombeton/issues/352) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#359](https://github.com/fidals/stroyprombeton/issues/359) is still not solved; solved: [#352](https://github.com/fidals/stroyprombeton/issues/352).

**Comment by 0pdd** [comment]
@duker33 all 2 puzzles are solved here: [#352](https://github.com/fidals/stroyprombeton/issues/352), [#359](https://github.com/fidals/stroyprombeton/issues/359).
