### ISSUE TITLE
tests_views.py:210-211: Take CatalogTags tests from SE....

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#340]
The puzzle `320-eb49c2d0` from #320 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/dec56f78a4a75c7e5f3d71a07bc3553e242bd3cf/stroyprombeton/tests/tests_views.py#L210-L211

The puzzle was created by duker33 on 17-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
stb already has `stroyprombeton.tests.tests_views.CatalogTags` tests set.
I'll refactor tests location, rm some doubling code and check if stb test semantic as full as se's one

**Comment by 0pdd** [comment]
@0pdd the puzzle [#406](https://github.com/fidals/stroyprombeton/issues/406) is still not solved.
