### ISSUE TITLE
Reduce test times

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#347]
Test of a master branch takes more than [30m](https://ci.fidals.com/fidals/stroyprombeton/476)

**Comment by artemiy312** [comment]
got the first batch of slow tests:
1. 906.03 test_tree_fetch_data (stroyprombeton.tests.tests_selenium_admin.AdminPage)
2. 905.53 test_tree_redirect_to_table_editor_page (stroyprombeton.tests.tests_selenium_admin.AdminPage)
3. 303.07 test_order_page_remove_all_products (stroyprombeton.tests.tests_selenium.OrderPage)
4. 301.39 test_inactive_product_not_in_search_autocomplete (stroyprombeton.tests.tests_selenium.Search)

**Comment by artemiy312** [comment]
Reached ~9 minutes

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#371](https://github.com/fidals/stroyprombeton/issues/371) is still not solved.

**Comment by 0pdd** [comment]
@artemiy312 the only puzzle [#371](https://github.com/fidals/stroyprombeton/issues/371) is solved here.
