### ISSUE TITLE
Divide execution of fast and slow tests.

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#348]
Stop a build process if fast tests fail. This will decrease tests execution time

**Comment by duker33** [comment]
@artemiy312 , create the same task for SE plz

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#358](https://github.com/fidals/stroyprombeton/issues/358) is still not solved.

**Comment by 0pdd** [comment]
@artemiy312 the only puzzle [#358](https://github.com/fidals/stroyprombeton/issues/358) is solved here.
