### ISSUE TITLE
Solve too many tags UI problem

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#362]
The obvious solution: create label `от 10м до 1000м` with no controls inside if we have too many tags

**Comment by duker33** [comment]
created test with functional requirements for this feature

**Comment by 0pdd** [comment]
@duker33 the puzzle [#374](https://github.com/fidals/stroyprombeton/issues/374) is still not solved.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#379](https://github.com/fidals/stroyprombeton/issues/379), [#380](https://github.com/fidals/stroyprombeton/issues/380) are still not solved; solved: [#374](https://github.com/fidals/stroyprombeton/issues/374).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#379](https://github.com/fidals/stroyprombeton/issues/379), [#380](https://github.com/fidals/stroyprombeton/issues/380) are still not solved; solved: [#234](https://github.com/fidals/stroyprombeton/issues/234), [#248](https://github.com/fidals/stroyprombeton/issues/248), [#374](https://github.com/fidals/stroyprombeton/issues/374).

**Comment by 0pdd** [comment]
@duker33 all 5 puzzles are solved here: [#234](https://github.com/fidals/stroyprombeton/issues/234), [#248](https://github.com/fidals/stroyprombeton/issues/248), [#374](https://github.com/fidals/stroyprombeton/issues/374), [#379](https://github.com/fidals/stroyprombeton/issues/379), [#380](https://github.com/fidals/stroyprombeton/issues/380).
