### ISSUE TITLE
tests_selenium.py:477: Resurrect `test_apply_filter_state`

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#380]
The puzzle `374-d720f0b9` from #374 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/27ede33c8beb9fa850c41030b668edac1889a492/stroyprombeton/tests/tests_selenium.py#L477-L477

The puzzle was created by duker33 on 17-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
test already works

**Comment by 0pdd** [comment]
The puzzle `374-d720f0b9` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33
