### ISSUE TITLE
Implement ProductOptions

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#396]
Arch was developed here: https://github.com/fidals/stroyprombeton/issues/330

**Comment by duker33** [comment]
i'll fix many Product model use cases at the same task

**Comment by duker33** [comment]
no, it's too many work. I'll create set of `@todo's` at different components.
And i'll make compatible, but not full changes at the models schema

**Comment by duker33** [comment]
blocked by segfault. See related PR

**Comment by duker33** [comment]
we'll downgrade to python 3.6

**Comment by 0pdd** [comment]
@duker33 9 puzzles [#413](https://github.com/fidals/stroyprombeton/issues/413), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#418](https://github.com/fidals/stroyprombeton/issues/418), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#424](https://github.com/fidals/stroyprombeton/issues/424) are still not solved; solved: [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#417](https://github.com/fidals/stroyprombeton/issues/417).

**Comment by 0pdd** [comment]
@duker33 8 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432) are still not solved; solved: [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417).

**Comment by 0pdd** [comment]
@duker33 8 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#433](https://github.com/fidals/stroyprombeton/issues/433) are still not solved; solved: [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#424](https://github.com/fidals/stroyprombeton/issues/424).

**Comment by 0pdd** [comment]
@duker33 8 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436) are still not solved; solved: [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436) are still not solved; solved: [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432).

**Comment by 0pdd** [comment]
@duker33 13 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#460](https://github.com/fidals/stroyprombeton/issues/460) are still not solved; solved: [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432).

**Comment by 0pdd** [comment]
@duker33 13 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#460](https://github.com/fidals/stroyprombeton/issues/460) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432).

**Comment by 0pdd** [comment]
@duker33 13 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#460](https://github.com/fidals/stroyprombeton/issues/460).

**Comment by 0pdd** [comment]
@duker33 17 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#460](https://github.com/fidals/stroyprombeton/issues/460).

**Comment by 0pdd** [comment]
@duker33 16 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460).

**Comment by 0pdd** [comment]
@duker33 15 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#491](https://github.com/fidals/stroyprombeton/issues/491).

**Comment by 0pdd** [comment]
@duker33 13 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#491](https://github.com/fidals/stroyprombeton/issues/491).

**Comment by 0pdd** [comment]
@duker33 12 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#490](https://github.com/fidals/stroyprombeton/issues/490) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492).

**Comment by 0pdd** [comment]
@duker33 13 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492).

**Comment by 0pdd** [comment]
@duker33 11 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590).

**Comment by 0pdd** [comment]
@duker33 10 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#591](https://github.com/fidals/stroyprombeton/issues/591) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#592](https://github.com/fidals/stroyprombeton/issues/592).

**Comment by 0pdd** [comment]
@duker33 10 puzzles [#418](https://github.com/fidals/stroyprombeton/issues/418), [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#615](https://github.com/fidals/stroyprombeton/issues/615) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592).

**Comment by 0pdd** [comment]
@duker33 9 puzzles [#420](https://github.com/fidals/stroyprombeton/issues/420), [#421](https://github.com/fidals/stroyprombeton/issues/421), [#422](https://github.com/fidals/stroyprombeton/issues/422), [#423](https://github.com/fidals/stroyprombeton/issues/423), [#436](https://github.com/fidals/stroyprombeton/issues/436), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#615](https://github.com/fidals/stroyprombeton/issues/615) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#413](https://github.com/fidals/stroyprombeton/issues/413), [#414](https://github.com/fidals/stroyprombeton/issues/414), [#415](https://github.com/fidals/stroyprombeton/issues/415), [#416](https://github.com/fidals/stroyprombeton/issues/416), [#417](https://github.com/fidals/stroyprombeton/issues/417), [#418](https://github.com/fidals/stroyprombeton/issues/418), [#419](https://github.com/fidals/stroyprombeton/issues/419), [#424](https://github.com/fidals/stroyprombeton/issues/424), [#432](https://github.com/fidals/stroyprombeton/issues/432), [#433](https://github.com/fidals/stroyprombeton/issues/433), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592).
