### ISSUE TITLE
Resolve segfault issue at CI tests

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#403]
This issue also will resolve this not auto created pdd issue:

Resurrect product.diameter_out field render
https://github.com/fidals/stroyprombeton/pull/391/files#diff-0935e97978f420ce3f93d59b1560e197R62

**Comment by duker33** [comment]
maybe it's some problem on alpine side:
https://github.com/docker-library/python/issues/211#issuecomment-314866095

**Comment by artemiy312** [comment]
We don't use alpine anywhere, do we?

**Comment by duker33** [comment]
@artemiy312 , seems we don't. I thought, that `python-slim` image is based on alpine, but it's not true.
Anyway, i should check if python's stack space as suggested in comment

**Comment by duker33** [comment]
this task is not related to my skills directly, but we have to solve it.
So, i'll fight with it for two or three full days

**Comment by artemiy312** [comment]
@duker33 Let's rollback to python 3.6 and resolve this issue when the time comes for it

**Comment by duker33** [comment]
@artemiy312 , i'll check if your's PR ahead fixes this issue.
I'll launch CI three times successively with the same code at the serv and on the local system.
If'll not fail, you resolved issue and we can move on

**Comment by duker33** [comment]
@artemiy312 , found your approvement if issue not resolved. Ok, let's just downgrade to python3.6, implement all hot tasks on STB and take it again

https://github.com/fidals/stroyprombeton/pull/408

**Comment by duker33** [comment]
moving from fields to tags resolves this issue automatically
