### ISSUE TITLE
catalog.py:20: Adapt views to Options

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#419]
The puzzle `396-420da051` from #396 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/196e6cb4f653274e81ff1cdef748345a721846a2/stroyprombeton/views/catalog.py#L20-L20

The puzzle was created by duker33 on 30-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
we should implement use SE's new context arch for the first

**Comment by 0pdd** [comment]
The puzzle `396-420da051` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#460](https://github.com/fidals/stroyprombeton/issues/460) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#460](https://github.com/fidals/stroyprombeton/issues/460) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280).

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#460](https://github.com/fidals/stroyprombeton/issues/460).

**Comment by 0pdd** [comment]
@0pdd 10 puzzles [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#460](https://github.com/fidals/stroyprombeton/issues/460).

**Comment by 0pdd** [comment]
@0pdd 9 puzzles [#455](https://github.com/fidals/stroyprombeton/issues/455), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460).

**Comment by 0pdd** [comment]
@0pdd 8 puzzles [#455](https://github.com/fidals/stroyprombeton/issues/455), [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#491](https://github.com/fidals/stroyprombeton/issues/491).

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#491](https://github.com/fidals/stroyprombeton/issues/491).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#490](https://github.com/fidals/stroyprombeton/issues/490) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#457](https://github.com/fidals/stroyprombeton/issues/457), [#458](https://github.com/fidals/stroyprombeton/issues/458), [#459](https://github.com/fidals/stroyprombeton/issues/459) are still not solved; solved: [#280](https://github.com/fidals/stroyprombeton/issues/280), [#455](https://github.com/fidals/stroyprombeton/issues/455), [#456](https://github.com/fidals/stroyprombeton/issues/456), [#460](https://github.com/fidals/stroyprombeton/issues/460), [#488](https://github.com/fidals/stroyprombeton/issues/488), [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492).
