### ISSUE TITLE
admin.py:178: Adapt admin panel to Options

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#424]
The puzzle `396-6d2bc254` from #396 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/196e6cb4f653274e81ff1cdef748345a721846a2/stroyprombeton/admin.py#L178-L178

The puzzle was created by duker33 on 30-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
I am going to integrate Options to Table editor here

**Comment by 0pdd** [comment]
@0pdd the puzzle [#433](https://github.com/fidals/stroyprombeton/issues/433) is still not solved.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592) are still not solved; solved: [#433](https://github.com/fidals/stroyprombeton/issues/433).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592) are still not solved; solved: [#433](https://github.com/fidals/stroyprombeton/issues/433), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#591](https://github.com/fidals/stroyprombeton/issues/591) is still not solved; solved: [#433](https://github.com/fidals/stroyprombeton/issues/433), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#592](https://github.com/fidals/stroyprombeton/issues/592).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#615](https://github.com/fidals/stroyprombeton/issues/615) is still not solved; solved: [#433](https://github.com/fidals/stroyprombeton/issues/433), [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592).
