### ISSUE TITLE
Use refarm's context

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#431]
Use the latest version. It's called newcontext now.

But we should finish newcontext using on SE for the first

**Comment by duker33** [comment]
blocked by https://github.com/fidals/shopelectro/issues/699

We are needed in fully complete example of context implementing before reusing it here

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#443](https://github.com/fidals/stroyprombeton/issues/443), [#444](https://github.com/fidals/stroyprombeton/issues/444), [#445](https://github.com/fidals/stroyprombeton/issues/445), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#447](https://github.com/fidals/stroyprombeton/issues/447) are still not solved.

**Comment by 0pdd** [comment]
@duker33 6 puzzles [#444](https://github.com/fidals/stroyprombeton/issues/444), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#447](https://github.com/fidals/stroyprombeton/issues/447), [#449](https://github.com/fidals/stroyprombeton/issues/449), [#450](https://github.com/fidals/stroyprombeton/issues/450), [#451](https://github.com/fidals/stroyprombeton/issues/451) are still not solved; solved: [#443](https://github.com/fidals/stroyprombeton/issues/443), [#445](https://github.com/fidals/stroyprombeton/issues/445).

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#444](https://github.com/fidals/stroyprombeton/issues/444), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#449](https://github.com/fidals/stroyprombeton/issues/449), [#450](https://github.com/fidals/stroyprombeton/issues/450), [#511](https://github.com/fidals/stroyprombeton/issues/511) are still not solved; solved: [#443](https://github.com/fidals/stroyprombeton/issues/443), [#445](https://github.com/fidals/stroyprombeton/issues/445), [#447](https://github.com/fidals/stroyprombeton/issues/447), [#451](https://github.com/fidals/stroyprombeton/issues/451).

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#444](https://github.com/fidals/stroyprombeton/issues/444), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#511](https://github.com/fidals/stroyprombeton/issues/511), [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515) are still not solved; solved: [#443](https://github.com/fidals/stroyprombeton/issues/443), [#445](https://github.com/fidals/stroyprombeton/issues/445), [#447](https://github.com/fidals/stroyprombeton/issues/447), [#449](https://github.com/fidals/stroyprombeton/issues/449), [#450](https://github.com/fidals/stroyprombeton/issues/450), [#451](https://github.com/fidals/stroyprombeton/issues/451).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#444](https://github.com/fidals/stroyprombeton/issues/444), [#511](https://github.com/fidals/stroyprombeton/issues/511), [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521), [#522](https://github.com/fidals/stroyprombeton/issues/522) are still not solved; solved: [#443](https://github.com/fidals/stroyprombeton/issues/443), [#445](https://github.com/fidals/stroyprombeton/issues/445), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#447](https://github.com/fidals/stroyprombeton/issues/447), [#449](https://github.com/fidals/stroyprombeton/issues/449), [#450](https://github.com/fidals/stroyprombeton/issues/450), [#451](https://github.com/fidals/stroyprombeton/issues/451), [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515).

**Comment by 0pdd** [comment]
@duker33 8 puzzles [#444](https://github.com/fidals/stroyprombeton/issues/444), [#511](https://github.com/fidals/stroyprombeton/issues/511), [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521), [#542](https://github.com/fidals/stroyprombeton/issues/542), [#543](https://github.com/fidals/stroyprombeton/issues/543) are still not solved; solved: [#443](https://github.com/fidals/stroyprombeton/issues/443), [#445](https://github.com/fidals/stroyprombeton/issues/445), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#447](https://github.com/fidals/stroyprombeton/issues/447), [#449](https://github.com/fidals/stroyprombeton/issues/449), [#450](https://github.com/fidals/stroyprombeton/issues/450), [#451](https://github.com/fidals/stroyprombeton/issues/451), [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515), [#522](https://github.com/fidals/stroyprombeton/issues/522).

**Comment by 0pdd** [comment]
@duker33 6 puzzles [#444](https://github.com/fidals/stroyprombeton/issues/444), [#511](https://github.com/fidals/stroyprombeton/issues/511), [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521) are still not solved; solved: [#443](https://github.com/fidals/stroyprombeton/issues/443), [#445](https://github.com/fidals/stroyprombeton/issues/445), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#447](https://github.com/fidals/stroyprombeton/issues/447), [#449](https://github.com/fidals/stroyprombeton/issues/449), [#450](https://github.com/fidals/stroyprombeton/issues/450), [#451](https://github.com/fidals/stroyprombeton/issues/451), [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515), [#522](https://github.com/fidals/stroyprombeton/issues/522), [#542](https://github.com/fidals/stroyprombeton/issues/542), [#543](https://github.com/fidals/stroyprombeton/issues/543).

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#444](https://github.com/fidals/stroyprombeton/issues/444), [#511](https://github.com/fidals/stroyprombeton/issues/511), [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#598](https://github.com/fidals/stroyprombeton/issues/598) are still not solved; solved: [#443](https://github.com/fidals/stroyprombeton/issues/443), [#445](https://github.com/fidals/stroyprombeton/issues/445), [#446](https://github.com/fidals/stroyprombeton/issues/446), [#447](https://github.com/fidals/stroyprombeton/issues/447), [#449](https://github.com/fidals/stroyprombeton/issues/449), [#450](https://github.com/fidals/stroyprombeton/issues/450), [#451](https://github.com/fidals/stroyprombeton/issues/451), [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515), [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521), [#522](https://github.com/fidals/stroyprombeton/issues/522), [#542](https://github.com/fidals/stroyprombeton/issues/542), [#543](https://github.com/fidals/stroyprombeton/issues/543).
