### ISSUE TITLE
admin.py:178: Integrate new Option model to django's admin.

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#433]
The puzzle `424-3f91fbfa` from #424 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/39167fbe11e503548c9243726805d9819840420f/stroyprombeton/admin.py#L178-L178

The puzzle was created by Artemiy on 07-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
released options already

**Comment by duker33** [comment]
remove `models.Product.price` field after integration

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592) are still not solved; solved: [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#591](https://github.com/fidals/stroyprombeton/issues/591) is still not solved; solved: [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#592](https://github.com/fidals/stroyprombeton/issues/592).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#615](https://github.com/fidals/stroyprombeton/issues/615) is still not solved; solved: [#589](https://github.com/fidals/stroyprombeton/issues/589), [#590](https://github.com/fidals/stroyprombeton/issues/590), [#591](https://github.com/fidals/stroyprombeton/issues/591), [#592](https://github.com/fidals/stroyprombeton/issues/592).
