### ISSUE TITLE
sitemaps.py:5: Adapt sitemaps for Option model.

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#436]
The puzzle `396-64050826` from #396 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/f8b0c29086cc97f8fe24ed5574b72dd546d7fe63/stroyprombeton/sitemaps.py#L5-L5

The puzzle was created by Artemiy on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
@duker33 , Will option urls be differ from product urls? If won't then we can close the issue, because we already display product's urls on sitemap

**Comment by duker33** [comment]
@artemiy312 , you are right, let's close it. It's your `15 mins` for research
