### ISSUE TITLE
context.py:47-51: Improve context classes arch. Move...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#449]
The puzzle `443-950c8195` from #443 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/2dd8517703edfa0b25e9a5a0bdd9dabfdd4d4b4b/stroyprombeton/context.py#L47-L51

The puzzle was created by duker33 on 21-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
i'll provide implementation at the same task

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521) are still not solved; solved: [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#598](https://github.com/fidals/stroyprombeton/issues/598) are still not solved; solved: [#514](https://github.com/fidals/stroyprombeton/issues/514), [#515](https://github.com/fidals/stroyprombeton/issues/515), [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521).
