### ISSUE TITLE
request_data.py:55-57: Check FetchProducts post params....

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#451]
The puzzle `443-3dae6fc3` from #443 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/2dd8517703edfa0b25e9a5a0bdd9dabfdd4d4b4b/stroyprombeton/request_data.py#L55-L57

The puzzle was created by duker33 on 21-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
i will write test at the same task

**Comment by 0pdd** [comment]
@0pdd the puzzle [#511](https://github.com/fidals/stroyprombeton/issues/511) is still not solved.
