### ISSUE TITLE
models.py:194: Cleanup product model after Options...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#455]
The puzzle `419-566f5d69` from #419 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/d14e96d8fbe74f7ab1ce279bcbef734212192752/stroyprombeton/models.py#L194-L194

The puzzle was created by @duker33 on 22-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
needed to touch many parts of the system

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#491](https://github.com/fidals/stroyprombeton/issues/491).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#490](https://github.com/fidals/stroyprombeton/issues/490), [#492](https://github.com/fidals/stroyprombeton/issues/492) are still not solved; solved: [#489](https://github.com/fidals/stroyprombeton/issues/489), [#491](https://github.com/fidals/stroyprombeton/issues/491).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#490](https://github.com/fidals/stroyprombeton/issues/490) is still not solved; solved: [#489](https://github.com/fidals/stroyprombeton/issues/489), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#489](https://github.com/fidals/stroyprombeton/issues/489), [#490](https://github.com/fidals/stroyprombeton/issues/490), [#491](https://github.com/fidals/stroyprombeton/issues/491), [#492](https://github.com/fidals/stroyprombeton/issues/492).
