### ISSUE TITLE
Regressions policy

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#464]
We have a problem with temporary regressions. There are microtasks, that breaking the part of current functionality. For example #335. If they won't break, they are already not microtasks.

I propose create `breaking` + `fixing` tags. Any `breaking` task should contain `fixing` pdd subtask.
And we'll push deploy button with hands only if all current breakings was fixed.

**Comment by duker33** [comment]
@artemiy312 , what do you think about it?

**Comment by artemiy312** [comment]
@duker33 These tags will make monitoring of such issues more convenient, but they won't work as prohibition to deployments, because we can accidentally don't notice them

**Comment by artemiy312** [comment]
I'd prefer to keep master branch in safe and work with breaking changes in another branch.
It would avoid accidental deployments, because CI won't create production images

**Comment by duker33** [comment]
separated branch seems to me not so simple decision. And right now, through one day, my tags proposition doesn't look good to me too.

We don't have to often do breaking changes, so let's just say "no deploying before date N" in chat.
If this situation happens, we always can rollback. And we have monitoring system to collect issues

**Comment by artemiy312** [comment]
@duker33 good, let's do it
