### ISSUE TITLE
Render tags on product page

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#465]
~Connect tags to options instead of products. Create fixtures for it.~
Fixtures already created. So, i'll use it to render tags on product page.

**Comment by duker33** [comment]
blocks moving `Tags` feature on stage and prod

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#469](https://github.com/fidals/stroyprombeton/issues/469), [#470](https://github.com/fidals/stroyprombeton/issues/470) are still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#470](https://github.com/fidals/stroyprombeton/issues/470) is still not solved; solved: [#469](https://github.com/fidals/stroyprombeton/issues/469).
