### ISSUE TITLE
product.html:95-96: Adapt order button to Options. Now...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#468]
The puzzle `335-112a70ee` from #335 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/ae45c60f5dd7dfabfe5c10a4f00c6613cfc2bf7f/templates/catalog/product.html#L95-L96

The puzzle was created by duker33 on 27-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
resurrect test too

**Comment by 0pdd** [comment]
@0pdd the puzzle [#526](https://github.com/fidals/stroyprombeton/issues/526) is still not solved.
