### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#478]
Change new logo on the whole site. Logo contains company name. All materials are here:
https://drive.google.com/drive/u/0/folders/1HSw5WV25a_LxybUY1OGjLjIc2Dj0JiQU

And rm info about the group of companies from the main page. See the screen
![image](https://user-images.githubusercontent.com/3526796/53625964-939c8900-3c15-11e9-9958-b6c4b8dfbdae.png)

**Comment by artemiy312** [comment]
@duker33 It seems something missed. The link doesn't contain a logo in a suitable format (`svg`, `png`, etc). It contains only pdf and adobe illustrator files

**Comment by duker33** [comment]
cut logos myself (i'm not graphical guy) from pdf's as Artemiy requested.
Hope it's enough for the site.

![logo_header_262x53](https://user-images.githubusercontent.com/3526796/53695982-5d0c6d00-3dd3-11e9-8a82-db91e50fa6de.png)
![logo_footer_165x36](https://user-images.githubusercontent.com/3526796/53695983-5d0c6d00-3dd3-11e9-900d-295518cad6f5.png)

**Comment by duker33** [comment]
i decided to move header part from grey color to white one. If business will mind, we'll include designers to logos creating
![image](https://user-images.githubusercontent.com/3526796/53697579-ac5a9980-3de3-11e9-9b83-1a0f26d87381.png)

**Comment by duker33** [comment]
increased task estimate. It's burning and Artemiy had a lot of work, not directly related to task dev

**Comment by artemiy312** [comment]
I didn't apply padding for new logo files, because otherwise they will look disproportionately big relative to other elements of the site

**Comment by artemiy312** [comment]
final view

<img width="1280" alt="default" src="https://user-images.githubusercontent.com/13870342/53697841-a74b1980-3de6-11e9-8c0b-048b9b6137fb.png">
<img width="1280" alt="default" src="https://user-images.githubusercontent.com/13870342/53697843-ad40fa80-3de6-11e9-9550-a49bcd4afdf1.png">
