### ISSUE TITLE
Move product props to an option tags

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#483]
This is the last task left to release Tags functionality to the prod

**Comment by duker33** [comment]
we don't have options data yet. So, depends on #483

**Comment by duker33** [comment]
seems migrations don't call save (and any) method of model:
https://stackoverflow.com/questions/32010854/django-model-save-override-method-not-invoked-during-migrations

It means, that we should move data migrations throw django command. I'll provide it as astronomical hours

**Comment by duker33** [comment]
moved it to command, but models in command have wrong version.
So, i'll repeat slugify functions at migrations with plain code

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#493](https://github.com/fidals/stroyprombeton/issues/493), [#494](https://github.com/fidals/stroyprombeton/issues/494), [#495](https://github.com/fidals/stroyprombeton/issues/495), [#496](https://github.com/fidals/stroyprombeton/issues/496), [#497](https://github.com/fidals/stroyprombeton/issues/497), [#498](https://github.com/fidals/stroyprombeton/issues/498), [#499](https://github.com/fidals/stroyprombeton/issues/499) are still not solved.

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#493](https://github.com/fidals/stroyprombeton/issues/493), [#494](https://github.com/fidals/stroyprombeton/issues/494), [#497](https://github.com/fidals/stroyprombeton/issues/497), [#498](https://github.com/fidals/stroyprombeton/issues/498), [#499](https://github.com/fidals/stroyprombeton/issues/499), [#529](https://github.com/fidals/stroyprombeton/issues/529), [#530](https://github.com/fidals/stroyprombeton/issues/530) are still not solved; solved: [#495](https://github.com/fidals/stroyprombeton/issues/495), [#496](https://github.com/fidals/stroyprombeton/issues/496).

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#493](https://github.com/fidals/stroyprombeton/issues/493), [#494](https://github.com/fidals/stroyprombeton/issues/494), [#497](https://github.com/fidals/stroyprombeton/issues/497), [#546](https://github.com/fidals/stroyprombeton/issues/546) are still not solved; solved: [#495](https://github.com/fidals/stroyprombeton/issues/495), [#496](https://github.com/fidals/stroyprombeton/issues/496), [#498](https://github.com/fidals/stroyprombeton/issues/498), [#499](https://github.com/fidals/stroyprombeton/issues/499), [#529](https://github.com/fidals/stroyprombeton/issues/529), [#530](https://github.com/fidals/stroyprombeton/issues/530).

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#493](https://github.com/fidals/stroyprombeton/issues/493), [#494](https://github.com/fidals/stroyprombeton/issues/494), [#497](https://github.com/fidals/stroyprombeton/issues/497), [#594](https://github.com/fidals/stroyprombeton/issues/594) are still not solved; solved: [#495](https://github.com/fidals/stroyprombeton/issues/495), [#496](https://github.com/fidals/stroyprombeton/issues/496), [#498](https://github.com/fidals/stroyprombeton/issues/498), [#499](https://github.com/fidals/stroyprombeton/issues/499), [#529](https://github.com/fidals/stroyprombeton/issues/529), [#530](https://github.com/fidals/stroyprombeton/issues/530), [#546](https://github.com/fidals/stroyprombeton/issues/546).
