### ISSUE TITLE
models.py:31-32: Explore `Category.specification` field...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#494]
The puzzle `483-11f026a3` from #483 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/bc0f7a6b62c28515ad5e06bd11e6e21812b30a2d/stroyprombeton/models.py#L31-L32

The puzzle was created by duker33 on 11-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
production db contains only four categories with specification field, that is not the part of name:
```
Открытый цех по переработке сыпучих навалочных грузов промышленных предприятий. Рабочая документация: ТП 709-9-126.93. Альбом 3 | Рабочая документация: ТП 709-9-126.93 Альбом 3
Колодцы водопроводные. ТПР 901-09-11.84 | ТПР 901-09-11.84
Затопленный водоприёмник раструбный производительностью от 0,02 до 0,3 м3/с. ТП 901-1-60.86 | ТП 901-1-60.86
Колонны железобетонные для открытых крановых эстакад. Серия 3.013.9-1. Выпуск 1 | Рабочая документация: Серия 3.013.9-1. Выпуск 1
```

**Comment by duker33** [comment]
And it's from prod:
```
> Category.objects.exclude(specification='').filter(children__isnull=False).count()
142
```

It means that DB contains not leaf categories with not empty specification field

**Comment by duker33** [comment]
i'll resolve this field at #510
