### ISSUE TITLE
Product page bad performance

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#500]
Product page got bad performance after Options and Tags features deploy

**Comment by duker33** [comment]
localized problem. It's because of this piece of code:

```
# templates/catalog/product.html

{% for tag in option.tags.all %}
  {% if tag in group.tags.all %}
    {{ tag.name }}
  {% endif %}
{% endfor %}
```

**Comment by duker33** [comment]
this is current length count of every tag group
![image](https://user-images.githubusercontent.com/3526796/54193332-e3f3d080-44ca-11e9-9485-3aaa9b4d89ad.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#504](https://github.com/fidals/stroyprombeton/issues/504) is still not solved.
