### ISSUE TITLE
Unstable selenium tests

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#505]
Random (as it seems to me) selenium tests regularly fail in CI.
But maybe it's some problem of `load_category_page` call.

https://ci.fidals.com/fidals/stroyprombeton/866/10

**Comment by duker33** [comment]
SE suffers from this problem too.
[This pipeline](https://ci.fidals.com/fidals/shopelectro/1369) was failed, but [this one](https://ci.fidals.com/fidals/shopelectro/1370) with the same code is success

**Comment by artemiy312** [comment]
I will implement a failed tests collector that will rerun them again to discard suspicions about random

**Comment by duker33** [comment]
@artemiy312 , be careful, maybe you'll face the problem from #506. Rerunning after 40 min is not good idea :) But maybe it's not relevant

**Comment by artemiy312** [comment]
It works as expected. You may see it [here](https://ci.fidals.com/fidals/shopelectro/1597/10): 
```
Rerun tries left: 1
Rerun these failed tests:
	- shopelectro.tests.tests_selenium.CategoryPage.test_cached_cart
```

**Comment by duker33** [comment]
`6:48` for the slow tests totally. Pretty good
