### ISSUE TITLE
context.py:207-210: Remove FetchPositions class. Create a...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#514]
The puzzle `449-e2222af9` from #449 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/b16eddfee8a4ba54f51a56f0dca1a1736551e0fa/stroyprombeton/context.py#L207-L210

The puzzle was created by @duker33 on 18-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
left `context.FetchPositions` class, but fully separated it from `context.Category` one

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#518](https://github.com/fidals/stroyprombeton/issues/518), [#519](https://github.com/fidals/stroyprombeton/issues/519), [#598](https://github.com/fidals/stroyprombeton/issues/598) are still not solved; solved: [#520](https://github.com/fidals/stroyprombeton/issues/520), [#521](https://github.com/fidals/stroyprombeton/issues/521).
