### ISSUE TITLE
tests_views.py:161-163: Create catalog pagination tests....

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#522]
The puzzle `446-0314230a` from #446 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/c5d7475a79ea196fdc0035de71b7e0a31c22bac8/stroyprombeton/tests/tests_views.py#L161-L163

The puzzle was created by duker33 on 20-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
high priority because some functionality maybe broken

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#542](https://github.com/fidals/stroyprombeton/issues/542), [#543](https://github.com/fidals/stroyprombeton/issues/543) are still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#542](https://github.com/fidals/stroyprombeton/issues/542), [#543](https://github.com/fidals/stroyprombeton/issues/543).
