### ISSUE TITLE
Repair redirect from www.stk-modul.ru

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#524]
Сейчас перекидывает на гит. хз почему. 
Делай редирект на https://www.stroyprombeton.ru/
для www.stk-modul.ru и stk-modul.ru

**Comment by duker33** [comment]
@themygit , it's done. To check it clear browser cache or try this command. It'll show a part of stb site's html
```
curl -L -H 'Cache-Control: no-cache' www.stk-modul.ru | head -n 50
```
