### ISSUE TITLE
Category page contains raw template code

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#555]
Screen: http://prntscr.com/n1tjku

From this page:
https://www.stroyprombeton.ru/gbi/categories/47/tags/seriia__seriia-3_407_1_144_-vypusk-1/

**Comment by artemiy312** [comment]
It fixed here https://github.com/fidals/stroyprombeton/commit/d6c7e2e1beaa9d7ad1c0748a6dd1b9b1bd1ba2fe
