### ISSUE TITLE
Rm high level categories

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#556]
37 subcategories of the second level will become the high-level categories.

- [ ] Create more root categories with test_db to test it's presense at the UI.
- [ ] Move list to a matrix at the dropdown http://192.168.56.10:8020/gbi/
- [ ] Move list to a matrix on the catalog page http://192.168.56.10:8020/gbi/
- [ ] Deploy changes
- [ ] Create and run a script to move categories on the prod

**Comment by 0pdd** [comment]
@duker33 the puzzle [#567](https://github.com/fidals/stroyprombeton/issues/567) is still not solved.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#581](https://github.com/fidals/stroyprombeton/issues/581), [#582](https://github.com/fidals/stroyprombeton/issues/582) are still not solved; solved: [#567](https://github.com/fidals/stroyprombeton/issues/567).

**Comment by 0pdd** [comment]
@duker33 the puzzle [#593](https://github.com/fidals/stroyprombeton/issues/593) is still not solved; solved: [#567](https://github.com/fidals/stroyprombeton/issues/567), [#581](https://github.com/fidals/stroyprombeton/issues/581), [#582](https://github.com/fidals/stroyprombeton/issues/582).
