### ISSUE TITLE
Periodic 500 on every page on the prod

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#557]
Log says that:
```
ValueError: Missing staticfiles manifest entry for 'images/common/image-thumb.png'
```

Tried to do collectstatic several times

**Comment by artemiy312** [comment]
Server restart helped, I will consider this as astronomical time. It seems it was a cache issue

**Comment by duker33** [comment]
@artemiy312 , you restarted the whole server or just docker container?

**Comment by artemiy312** [comment]
@duker33 just docker container. Probably Nginx have cached an old version of a file, and then tried to get it, but the file was replaced with a new one. (e.g. `/favicon.04ef1628dd3e.ico -> collectstatic -> /favicon.e3dd8261fe40.ico`)

To avoid such behavior we should use `make deploy`
