### ISSUE TITLE
models.py:48-50: Create Series navigation. See the...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#558]
The puzzle `510-d7a1e1df` from #510 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/69d7520d94187050ad92581c48d986d9ce65213f/stroyprombeton/models.py#L48-L50

The puzzle was created by duker33 on 05-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
currently we 317 different series on the prod

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#599](https://github.com/fidals/stroyprombeton/issues/599), [#600](https://github.com/fidals/stroyprombeton/issues/600), [#601](https://github.com/fidals/stroyprombeton/issues/601) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#599](https://github.com/fidals/stroyprombeton/issues/599), [#600](https://github.com/fidals/stroyprombeton/issues/600) are still not solved; solved: [#601](https://github.com/fidals/stroyprombeton/issues/601).
