### ISSUE TITLE
Remove redundant h2

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#564]
Now we have the strange h2 with `display: none` on category page.
That's how it looks with disabled `display: none` css param

![image](https://user-images.githubusercontent.com/3526796/55666754-d88e8d80-585b-11e9-9563-5d56f671218f.png)

**Comment by duker33** [comment]
@themygit , should we drop it? If not, explain plz why

**Comment by themygit** [comment]
@duker33 yep. kill him.

**Comment by duker33** [comment]
it's done
