### ISSUE TITLE
Product images are broken

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#565]
On category and series pages.
Maybe it's because wrong product_images var in templates.

Expected behaviour:
- click on camera icon
- modal page with product image popups

Create autotest for it.

Category page from screen: https://www.stroyprombeton.ru/gbi/categories/459/

![image](https://user-images.githubusercontent.com/3526796/55668883-860f9a00-5878-11e9-821f-634a9acc5498.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#574](https://github.com/fidals/stroyprombeton/issues/574) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#574](https://github.com/fidals/stroyprombeton/issues/574) is solved here.
