### ISSUE TITLE
series.html:40-41: Rename `category_products.html` to...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#568]
The puzzle `560-497606ea` from #560 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/b82ec9976d33465440e90894d130e59c78d989c9/templates/catalog/series.html#L40-L41

The puzzle was created by duker33 on 07-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
i'll use "option", to name clearly option object. And "position", in cases when we know nothing about object: only that it's position
