### ISSUE TITLE
tests_views.py:959-960: Implement search on series. And...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#584]
The puzzle `570-e576fe87` from #570 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/2857a2cad29b58e4b082e318bffff0fe98f18eee/stroyprombeton/tests/tests_views.py#L959-L960

The puzzle was created by duker33 on 11-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
seems this feature is non relevant. I'll close it. If seo or UX/UI will require it, we'll implement
