### ISSUE TITLE
admin.py:244-245: Determine relevance of...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#591]
The puzzle `433-a94ade77` from #433 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/200016aeaa7eb7d06e9e6896bff6ab29d6231e83/stroyprombeton/admin.py#L244-L245

The puzzle was created by Artemiy on 11-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
`CharacteristicsEqualityFilter` finds duplicated options by `h1` or all fields. It still maybe helpful for content managers, so we should adopt it for Option model. 

 @duker33 Should we?

**Comment by duker33** [comment]
@artemiy312 , it depends on DB content: if we have at least one duplicated mark for any pair of Options, we should implement it. Otherwise not.

Explore plz this fact. If it's true, create subtask for Options implementation

**Comment by artemiy312** [comment]
```Python
In [1]: from django.db.models import Count

In [2]: from stroyprombeton.models import Option as O

In [3]: O.objects.values('mark').annotate(mark_count=Count('mark')).filter(mark_count__gt=1)
Out[3]: <OptionQuerySet [{'mark': 'Б-13', 'mark_count': 2}, {'mark': 'Ф6.201', 'mark_count': 2}, {'mark': 'ШЛП40п-9', 'mark_count': 3}, {'mark': '300ФП-1', 'mark_count': 2}, {'mark': 'РОП6.26-60', 'mark_count': 2}, {'mark': 'П-1-858', 'mark_count': 2}, {'mark': 'Ф5', 'mark_count': 5}, {'mark': '90Ш-1', 'mark_count': 2}, {'mark': 'ШТВ80.5', 'mark_count': 3}, {'mark': 'К15-3', 'mark_count': 2}, {'mark': '50СП-7в', 'mark_count': 4}, {'mark': 'Т6-4', 'mark_count': 2}, {'mark': 'Б-1а', 'mark_count': 2}, {'mark': 'ШТВ160.6', 'mark_count': 4}, {'mark': '50СП-7', 'mark_count': 2}, {'mark': 'Ф7.403', 'mark_count': 2}, {'mark': '9КФ175-1', 'mark_count': 2}, {'mark': 'К-3', 'mark_count': 2}, {'mark': 'К1-5', 'mark_count': 2}, {'mark': 'ТБ-1', 'mark_count': 2}, '...(remaining elements truncated)...']>

In [28]: O.objects.values('mark').annotate(mark_count=Count('mark')).filter(mark_count__gt=1).count()
Out[28]: 471
```

**Comment by artemiy312** [comment]
We have duplicated marks.
I'll adopt this filter in the issue, so i'll increase the estimate

**Comment by 0pdd** [comment]
@0pdd the puzzle [#615](https://github.com/fidals/stroyprombeton/issues/615) is still not solved.
