### ISSUE TITLE
Create links from Category page to the Series one

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#596]
We have no mockups for it. Use your own design solution

**Comment by duker33** [comment]
`2 hours`, because we have no mockup

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#609](https://github.com/fidals/stroyprombeton/issues/609), [#610](https://github.com/fidals/stroyprombeton/issues/610) are still not solved.

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#609](https://github.com/fidals/stroyprombeton/issues/609), [#610](https://github.com/fidals/stroyprombeton/issues/610), [#617](https://github.com/fidals/stroyprombeton/issues/617), [#618](https://github.com/fidals/stroyprombeton/issues/618), [#619](https://github.com/fidals/stroyprombeton/issues/619) are still not solved.

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#609](https://github.com/fidals/stroyprombeton/issues/609), [#617](https://github.com/fidals/stroyprombeton/issues/617), [#618](https://github.com/fidals/stroyprombeton/issues/618), [#619](https://github.com/fidals/stroyprombeton/issues/619) are still not solved; solved: [#610](https://github.com/fidals/stroyprombeton/issues/610).

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#609](https://github.com/fidals/stroyprombeton/issues/609), [#617](https://github.com/fidals/stroyprombeton/issues/617), [#618](https://github.com/fidals/stroyprombeton/issues/618), [#631](https://github.com/fidals/stroyprombeton/issues/631) are still not solved; solved: [#610](https://github.com/fidals/stroyprombeton/issues/610), [#619](https://github.com/fidals/stroyprombeton/issues/619).
