### ISSUE TITLE
Create link from Product page to the Series one

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#597]
We have no mockups for it. Use your own design solution

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#611](https://github.com/fidals/stroyprombeton/issues/611), [#612](https://github.com/fidals/stroyprombeton/issues/612), [#613](https://github.com/fidals/stroyprombeton/issues/613) are still not solved.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#612](https://github.com/fidals/stroyprombeton/issues/612), [#613](https://github.com/fidals/stroyprombeton/issues/613) are still not solved; solved: [#611](https://github.com/fidals/stroyprombeton/issues/611).
