### ISSUE TITLE
catalog.py:190-194: Filter options by category on Series...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#610]
The puzzle `596-2284720f` from #596 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/8a4af5cc00dee4ff9b665b9d34678a8e5e1d1c93/stroyprombeton/views/catalog.py#L190-L194

The puzzle was created by duker33 on 16-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
that's how series+category looks like
![image](https://user-images.githubusercontent.com/3526796/56228470-9269d300-6080-11e9-84c3-301abe824ba1.png)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#617](https://github.com/fidals/stroyprombeton/issues/617), [#618](https://github.com/fidals/stroyprombeton/issues/618), [#619](https://github.com/fidals/stroyprombeton/issues/619) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#617](https://github.com/fidals/stroyprombeton/issues/617), [#618](https://github.com/fidals/stroyprombeton/issues/618), [#631](https://github.com/fidals/stroyprombeton/issues/631) are still not solved; solved: [#619](https://github.com/fidals/stroyprombeton/issues/619).
