### ISSUE TITLE
models.py:61-63: Check mptt's `get_descendants` default...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#611]
The puzzle `597-ce108e86` from #597 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/8a4af5cc00dee4ff9b665b9d34678a8e5e1d1c93/stroyprombeton/models.py#L61-L63

The puzzle was created by duker33 on 16-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
checked with `assertNumQueries` test. Prefetches on our side are not required

**Comment by duker33** [comment]
found out, that i used `assertNumQueries` wrongly.
Here is the most optimal version:
```
...
.filter(product__category__in=(
	Category.objects
	.select_related('parent')
	.filter(id=self.id)
	.get_descendants(include_self=True)
	.active()
)
...
```

I've getten rid from `.prefetch_related('children')`. It takes one additional query but not used
