### ISSUE TITLE
Post release minor fixes

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#622]
Set of minor prod issues to fix:
- [x] Empty All Series page https://www.stroyprombeton.ru/gbi/series/
- [x] No h1 on a Series page https://www.stroyprombeton.ru/gbi/series/tp-501_01_6_89_-albomy-2_-3/category/199/
- [x] No h1 on Category page too https://www.stroyprombeton.ru/gbi/categories/15151/
- [x] Periodical 500 on the prod
----- pdd hours -----
- [x] No option names on search page: https://www.stroyprombeton.ru/search/?term=%D0%B1%D0%B0%D0%BB%D0%BA%D0%B0
- [x] Category with no active products is visible: https://www.stroyprombeton.ru/gbi/categories/49/
- [x] (#619) Series with no active options is visible: https://www.stroyprombeton.ru/gbi/series/gost-6665_91/category/49/
- [x] Wrong link to the full series http://prntscr.com/ndjxqf
- [x] Show the mark field on a Product page http://prntscr.com/ndjn3g

**Comment by duker33** [comment]
i'll log a part of this task with astronomical hours.
When list will become stable, i'll estimate it with pdd hours and implement fixes

**Comment by duker33** [comment]
logs the rest of bugs with pdd hours

**Comment by 0pdd** [comment]
@duker33 the puzzle [#632](https://github.com/fidals/stroyprombeton/issues/632) is still not solved.
