### ISSUE TITLE
Fix wrong template for search

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#626]
It's from prod with enabled templates debug. This message is repeated in the search form on every page:
`DEBUG WARNING: undefined template variable [query] not found`

![image](https://user-images.githubusercontent.com/3526796/56357095-4f744080-61e3-11e9-9255-d704f7288e7e.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#634](https://github.com/fidals/stroyprombeton/issues/634) is still not solved.
