### ISSUE TITLE
Wrong breadcrumbs on product page

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#644]
This product has no categories at breadcrumbs:
https://www.stroyprombeton.ru/gbi/products/14131/

But it has category in real: https://www.stroyprombeton.ru/gbi/categories/402/

**Comment by duker33** [comment]
can't reproduce it on a local app. Checking the DB

**Comment by duker33** [comment]
we have problems with mptt tree meta data:
```
>>> from stroyprombeton.models import Product
>>>
>>> p = Product.objects.get(id=14131)
>>> page = p.page
>>> result = []
>>> while page:
...     page = page.parent
...     result.append(page)
...
print(p.page.get_ancestors(include_self=False))
>>> print(result)
[<Page: kanaly-i-tonneli-sbornye-iz-lotkovykh-elementov>, <Page: teplosnabzhenie-i-elektrosnabzhenie>, <Page: stroitelstvo-inzhenernykh-setei>, <Page: gbi>, None]
>>> print(p.page.get_ancestors(include_self=False))
<PageQuerySet []>
```

**Comment by duker33** [comment]
explored DB on the prod

**Comment by artemiy312** [comment]
Probably we should try to rebuild mptt tree. See [this](https://django-mptt.readthedocs.io/en/latest/models.html?highlight=rebuild#rebuild)

**Comment by duker33** [comment]
@artemiy312 , it helped. Now crumbs look good without dirty fix from the related PR
