### ISSUE TITLE
Change metatags templates

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#653]
На тех страницах где нет цен, заменяем "Цены от: [минимальная цена] руб" на "По минимальной цене".

-- --

1. Для страниц категорий: 
- родитель https://www.stroyprombeton.ru/gbi/categories/457/
- категория https://www.stroyprombeton.ru/gbi/categories/31/
- подкатегория https://www.stroyprombeton.ru/gbi/categories/38/
Шаблон:
Title: [h1] – низкие цены от производителя. Купить с доставкой по Москве, Санкт-Петербург и всей России
Description: 🚩 Купить [h1]: [Серия 1], [Серия 2], [Серия 3], и других серий на заводе железобетонных изделий «СТК Модуль». Цены от: [минимальная цена] руб
Keywords: [h1]

Например:
Title: Водоотводные сооружения - низкие цены от производителя. Купить с доставкой по Москве, Санкт-Петербург и всей России
Description: 🚩 Купить Водоотводные сооружения: Альбом 819, Альбом инв. №984, Альбом инв. №984 (дополнение), и других серий на заводе железобетонных изделий «СТК Модуль». Цены от: 515 руб.
Keywords: Водоотводные сооружения

Т.к. серий может быть много на странице, нет смысла перечислять их все в дескрипшене. Поэтому перечисляем только первые три.

2. Для страниц продуктов: 
- карточка https://www.stroyprombeton.ru/gbi/products/1302/

Шаблон:
Title: [h1], серия: [Серия] – низкие цены от производителя. Купить с доставкой по Москве, Санкт-Петербург и всей России
Description:  🚩 Купить [h1]: [Марка 1], [Марка 2], [Марка 3], и других марок. Серия: [Серия]. Цены от: [минимальная цена] руб.
Keywords: [h1], [Серия]

Например:
Title: Лоток междупутный железобетонный (ll тип), серия: Альбом инв. №984 – низкие цены от производителя. Купить с доставкой по Москве, Санкт-Петербург и всей России
Description:  🚩 Купить Лоток междупутный железобетонный (ll тип): Л075(МПЛ 0.75), Л125(МПЛ 1.25), Л150(МПЛ 1.50), и других марок. Серия: Альбом инв. №984. Цены от: 3630 руб.
Keywords: Лоток междупутный железобетонный (ll тип), Альбом инв. №984

Т.к. марок может быть много на странице, нет смысла перечислять их в дескрипшене. Поэтому перечисляем только первые три.

3. Для страниц серий:
-  https://www.stroyprombeton.ru/gbi/series/seriia-3_503_1_85_-vypusk-1/ 

Шаблон:
Title: Железобетонные изделия [h1]. Купить с доставкой по Москве, Санкт-Петербург и всей России
Description: 🚩 Купить изделия [h1] на заводе железобетонных изделий «СТК Модуль». Цены от: [минимальная цена] руб.
Keywords: [h1]
Например:
Title: Железобетонные изделия Серия 3.503.1-85, выпуск 1. Купить с доставкой по Москве, Санкт-Петербург и всей России
Description: 🚩 Купить изделия Серия 3.503.1-85, выпуск 1 на заводе железобетонных изделий «СТК Модуль». Цены от: 4885 руб.
Keywords: Серия 3.503.1-85, выпуск 1

Страницы вида серия+каталог (https://www.stroyprombeton.ru/gbi/series/albom-inv_-no-984/category/38/) пускай остаются закрытыми для индексации при помощи каноникла. Т.е. оставляем как сейчас.

**Comment by duker33** [comment]
`docx` is lovely format. Moved it's content to the task body

**Comment by duker33** [comment]
@themygit , seo guys can change do this changes via DB Templates. As it's working on SE right now:
https://www.stroyprombeton.ru/admin/pages/pagetemplate/

**Comment by duker33** [comment]
@themygit answered:
-- --
я понимаю, что это работает. Но разумней попросить тебя потратить 10 минут времени, чем учить их делать то, что мы делаем раз в пол года-год. а еще возможно где-то косячнуть и просить вас перепроверить.
-- --
seems guys are in hurry. So, i'll do it for them as fast as i can

**Comment by duker33** [comment]
maybe this features will be required:
- Series list on category pate
- marks list on product page
- min price on every page

**Comment by duker33** [comment]
@themygit , i fixed the text for a little. Note plz the fix: `Санкт-Петербург` -> `Санкт-Петербургу`

**Comment by duker33** [comment]
i've cutten series and marks iteration purity.
That's why you can find two commas in a row. Example from [this page's](https://www.stroyprombeton.ru/gbi/products/1284/) description metatag: `П-1, ,  и`

**Comment by duker33** [comment]
left `Цены от: [минимальная цена] руб` functionality for #659
