### ISSUE TITLE
Add names to the siblings list

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#656]
В карточках https://www.stroyprombeton.ru/gbi/products/1284/ в нижней перелинковке http://prntscr.com/npsjw1 выводить карточки той серии, к которой относится карточка http://prntscr.com/npsk9v. В данном случае со страницы https://www.stroyprombeton.ru/gbi/series/seriia-3_503_1_66/

И добавить название изделий http://prntscr.com/npsktc

Если в серии один товар - выводить эту же карту и линковать на себя.

**Comment by duker33** [comment]
@themygit , we already show options siblings pretty from the same series. But the siblings list has not the same sorting as it's series has. So, i'll fix sorting and show product names

**Comment by duker33** [comment]
seems reqs are right about series. Siblings have taken from category, not from series. Fixed it.
Lack of name in siblings card was bug. Fixed it too.
Now name looks like this
![image](https://user-images.githubusercontent.com/3526796/58031743-b90ca500-7b29-11e9-805b-b81fd0095a0d.png)

**Comment by duker33** [comment]
and the moment about sibling's price. Siblings are products, not options. They have no price.
We can delete price label or create some `Цена от ...` label. Ask PO about it too

**Comment by duker33** [comment]
> Lack of name in siblings card was bug. Fixed it too.

all html was ready before

**Comment by duker33** [comment]
seems rebasing siblings on Series is not as trivial as i suggested

**Comment by 0pdd** [comment]
@themygit the puzzle [#664](https://github.com/fidals/stroyprombeton/issues/664) is still not solved.
