### ISSUE TITLE
Hide empty series from the series list

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#662]
https://www.stroyprombeton.ru/series/

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#683](https://github.com/fidals/stroyprombeton/issues/683), [#685](https://github.com/fidals/stroyprombeton/issues/685) are still not solved.

**Comment by 0pdd** [comment]
@duker33 all 2 puzzles are solved here: [#683](https://github.com/fidals/stroyprombeton/issues/683), [#685](https://github.com/fidals/stroyprombeton/issues/685).
