### ISSUE TITLE
Cart order button on the product page don't work

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#665]
https://www.stroyprombeton.ru/gbi/products/12378/
Сейчас, можно добавить только первый товар. и то, он заезжает в корзину без серии и марки.

**Comment by duker33** [comment]
i'll create test for it

**Comment by duker33** [comment]
depends on https://github.com/fidals/stroyprombeton/issues/675

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#373](https://github.com/fidals/stroyprombeton/issues/373), [#681](https://github.com/fidals/stroyprombeton/issues/681) are still not solved.

**Comment by 0pdd** [comment]
@themygit 4 puzzles [#373](https://github.com/fidals/stroyprombeton/issues/373), [#681](https://github.com/fidals/stroyprombeton/issues/681), [#684](https://github.com/fidals/stroyprombeton/issues/684), [#686](https://github.com/fidals/stroyprombeton/issues/686) are still not solved.

**Comment by 0pdd** [comment]
@themygit 3 puzzles [#373](https://github.com/fidals/stroyprombeton/issues/373), [#681](https://github.com/fidals/stroyprombeton/issues/681), [#684](https://github.com/fidals/stroyprombeton/issues/684) are still not solved; solved: [#686](https://github.com/fidals/stroyprombeton/issues/686).

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#373](https://github.com/fidals/stroyprombeton/issues/373), [#681](https://github.com/fidals/stroyprombeton/issues/681) are still not solved; solved: [#684](https://github.com/fidals/stroyprombeton/issues/684), [#686](https://github.com/fidals/stroyprombeton/issues/686).
