### ISSUE TITLE
Change location on the contact's yandex map

### ISSUE THREAD

**Issue by themygit** [fidals/stroyprombeton#680]
Change the factory location on the yandex map on the "contacts" page.
The detailed description from PO:
-- --
В контактах поменяй второй адрес 
с 
пос.им.Свердлова, промышленная зона, улица Овцынская
на 
188676, Ленинградская область, Всеволожский район, п. Щеглово, ул. Дизельная, д.2.

**Comment by duker33** [comment]
admin page can do it
