### ISSUE TITLE
Return back template field values

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#692]
http://client.webit.ru/?act=8#que_id=99445

Seo guys asked us to improve page template fields with minor price function. But all price template code disappeared from DB by mysterious reasons.
We created templates with fields at https://github.com/fidals/stroyprombeton/issues/653

- return back disappeared prices functionality
- write "По минимальной цене" if min_price does not exists

**Comment by duker33** [comment]
met the problem with admin crazy mode https://github.com/fidals/stroyprombeton/issues/658
Fixing DB from the CLI now

**Comment by duker33** [comment]
`Category.get_min_price` does not work as expected. It returns 0.0 price for every non-leaf category.
I'll create subtask with test about it. For a while every non-leaf category in templates will contain no min prices

**Comment by 0pdd** [comment]
@duker33 the puzzle [#697](https://github.com/fidals/stroyprombeton/issues/697) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#697](https://github.com/fidals/stroyprombeton/issues/697) is solved here.
