### ISSUE TITLE
Create Sections

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#699]
Let's call flat categories as _Sections_. They have the same functionality as Series. But they are binded to products instead of Options.

"Трубы", "Плиты", "Квадратные плиты" are examples of Section

**Comment by duker33** [comment]
i'll create as much functionality as i can

**Comment by 0pdd** [comment]
@duker33 the puzzle [#704](https://github.com/fidals/stroyprombeton/issues/704) is still not solved.

**Comment by duker33** [comment]
resolved with https://github.com/fidals/stroyprombeton/pull/700

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#704](https://github.com/fidals/stroyprombeton/issues/704) is solved here.
