### ISSUE TITLE
catalog.py:267-268: Create sections navigation. Top menu...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#701]
The puzzle `669-02688a32` from #669 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/dde62565f22a501564b7f742b8236936393e8c76/stroyprombeton/views/catalog.py#L267-L268

The puzzle was created by @duker33 on 26-Jun-19. 

Estimate: 120 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
i needed one more additional menu item. That's how i resolved it. It's the temporary decision. UX guys will guide us to resolve it in clear way.

![New temporary header](https://user-images.githubusercontent.com/3526796/60520377-f1d59780-9ced-11e9-95d4-3a82921ab394.png)

![Current production header](https://user-images.githubusercontent.com/3526796/60520425-0a45b200-9cee-11e9-8a50-fb4b8e2a4141.png)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#721](https://github.com/fidals/stroyprombeton/issues/721) is still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#724](https://github.com/fidals/stroyprombeton/issues/724), [#725](https://github.com/fidals/stroyprombeton/issues/725) are still not solved; solved: [#721](https://github.com/fidals/stroyprombeton/issues/721).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#725](https://github.com/fidals/stroyprombeton/issues/725) is still not solved; solved: [#721](https://github.com/fidals/stroyprombeton/issues/721), [#724](https://github.com/fidals/stroyprombeton/issues/724).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#721](https://github.com/fidals/stroyprombeton/issues/721), [#724](https://github.com/fidals/stroyprombeton/issues/724), [#725](https://github.com/fidals/stroyprombeton/issues/725).
