### ISSUE TITLE
Fix phones line breaks on the top menu

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#712]
![image](https://user-images.githubusercontent.com/3526796/60173929-8df82e00-9818-11e9-9c6e-6499b3e1b54d.png)

**Comment by artemiy312** [comment]
@duker33 Can't reproduce the issue. Is it chrome?

**Comment by duker33** [comment]
@artemiy312 , sorry, it's chrome `75.0.3770.100`

**Comment by artemiy312** [comment]
@duker33 I can't still reproduce the issue. Probably it is some OS related thing

**Comment by duker33** [comment]
my Firefox has not this issue
![image](https://user-images.githubusercontent.com/3526796/60986847-08f93280-a349-11e9-8ea7-56bdac80f2cc.png)

**Comment by duker33** [comment]
found issue. It's because of my personal font sizes in chrome. I suggest that my case with a custom font size is not interesting for us
![image](https://user-images.githubusercontent.com/3526796/60987254-e7e51180-a349-11e9-8100-538231358f8e.png)
