### ISSUE TITLE
Research catalog classes redesigning

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#723]
We have three structures: Categories, Series and Sections.
Some of their features are similar, some - not.

Let's see on their problems.

**1. Series-Sections code doubling**
During Sections creating we faced with the code doubling problem. It seems Series and Sections semantically are too similar to have their own MVC code pipeline.

**2. Series extension**
`stalbeton.pro` site shows us that Series are just a part of the more general Working documentation (Рабочая документация) concept. See the screen. We should somehow generalize the concept of Series. Maybe we should do it together with Categories and Sections concepts

Now let's see how Category-Series-Section are similar and different.

- Category is hierarchical. Bound to product
- Series is flat. Bound to options
- WorkDoc (future Series) is two leveled. Bound to options
- Section is flat. Bound to products

And some about Series-Options relation. At the time we created Series we supposed that they should be bound to options. But DB analysis (see the tasks with tag `Data`) says that in fact they are bound to products.
So, maybe we'll move them to products. Maybe stalbeton data analysis will be required to make this decision.

![work doc structure](https://user-images.githubusercontent.com/3526796/60708504-e0bb9f00-9f16-11e9-98f6-d45e89e7aced.png)

**Comment by duker33** [comment]
the result of this task is arch decision presented with short text comment.
I've financed this task creation with astronomical time.
@artemiy312 , and i will take each for 0.5 pdd-h to discuss the task

**Comment by duker33** [comment]
this is my proposition:
- create WorkDoc model with two hierarchy levels
- move current series and sections to the WorkDoc
- leave sections at the top menu with some `WorkDoc.in_top_menu` bool field
- WorkDoc will be related to products, not options

**Comment by artemiy312** [comment]
@duker33 
>move current series and sections to the WorkDoc
leave sections at the top menu 

Will a WorkDoc list look so?:
```markdown
                  - Серии ->  products
                  - Балки ->  products
WorkDoc     ->    - Блоки ->  products      
                  - Колонны ->  products
                  - ... ->  products
```

`Серии` looks inappropriate in the list, don't you think so?

**Comment by duker33** [comment]
@artemiy312 , i assume this structure:
```
WorkDoc
    - Серия
        - Серия 1
        - Серия 2
        - Серия 3
        ...
    - Альбом
        - Альбом 1
        ...
    - ТП
        ...
    - Типы изделий
        - Балки
        - Колонны
        - Плиты
        ...
```

**Comment by duker33** [comment]
what is interesting is that stalbetorn.pro has much more simple, but the same effective structure.
Our structure is so complicated because i don't (now hope didn't) understand what is Series and how Categories hierarchy (content, not schema) is designed.

It is theirs structure in few words:
- Just two models: Category and CategoriesGroup
- Category examples: `Дорожное строительство, Балки, Плиты, Серия 1234, Альбом 987`
- Products (our Options) are related only to categories
- CategoriesGroup examples: `Альбом, ГОСТ, Серия, ТП`
- CategoryGroup related to Category as 1:n, relation may be empty
- See the screen at the task body. The central column is the list of CategoriesGroup
- Our Sections is just their list of second level (non root) categories

They should have split Products on Options as we does. But theirs Catalog hierarchy is much more simple and effective.

@artemiy312 , i propose to take theirs structure. It'll make our code much more simple.
We should make some research before. For example to prove that every Series have only one Category. But most probably data will allow structure simplifying. Since stalbeton could do it

**Comment by duker33** [comment]
spent additional time to research stalbeton structure

**Comment by artemiy312** [comment]
@duker33 Their structure looks good. But we should know for sure, that all categories will have the same functionality requirements, otherwise it will lead to ugly if-else branches by name/id/... to specify some functions for a certain category

As an alternative option to get rid of code duplication we could introduce an model/qs interfaces to bring polymorphism for great good :)
e.g.
```python
class MatrixQS(abc.ABC):
    """Implement some common functions"""
    def partition(self, columns):
        """Partition object for matrix view"""
        return ...
    def matrix(self):
        """Query objects for matrix view"""
        return ...

class SeriesQS(QuerySet, MatrixQS):
    # don't change here implementation

class SectionQS(QuerySet, MatrixQS):
    # don't change here implementation

class BrandNewHierarchyQS(QuerySet, MatrixQS):
    def partition(self, columns):
        '''Specific partition for BrandNewHierarchy model'''
        return ...
    def matrix(self):
        '''Specific matrix for BrandNewHierarchy model'''
        return ...

# single view for different models
def matrix_view(request, page_name, model):
    """"A model's manager implements MatrixQS interface"""
    columns = settings.SERIES_MATRIX_COLUMNS_COUNT
    page = CustomPage.objects.get(slug=page_name)
    matrix = model.objects.matrix()
    return render(
        request,
        'catalog/matrix.html',
        {
            'page': page,
            'parted_items': matrix.partition(columns),
        }
    )

# urls
urls = [
    custom_page_url(r'^(?P<page>series)/$', views.matrix_view, kwargs={'models': Series}),
    custom_page_url(r'^(?P<page>series)/$', views.matrix_view, kwargs={'models': Section}),
    custom_page_url(r'^(?P<page>brand_new_hierarchy)/$', views.matrix_view, kwargs={'models': BrandNewHierarchy}),
]
```

`BrandNewHierarchy` is a model with unique matrix queries and partition algorithm.

**Comment by artemiy312** [comment]
If `Categories` has the same functions, I will vote for the stalbetorn approach

**Comment by duker33** [comment]
@artemiy312 , i'm starting to implement stalbeton's DB structure.

We also can use a polymorphed models/QS's by the way of implementing

**Comment by duker33** [comment]
that's decided: we implement stalbeton's approach described at https://github.com/fidals/stroyprombeton/issues/723#issuecomment-508773473 with the small research before
