### ISSUE TITLE
section.html:9-10: Show categories list from section...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#724]
The puzzle `721-c5864803` from #721 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/d6630d65a4cdc01040810cbdb51d5efeb7dc778b/templates/catalog/section.html#L9-L10

The puzzle was created by @duker33 on 05-Jul-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
seems it's not required. I'll rm task from code

**Comment by 0pdd** [comment]
The puzzle `721-c5864803` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33
