### ISSUE TITLE
tests_views.py:302-303: Fix category links on series....

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#725]
The puzzle `721-947d61a9` from #721 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/d6630d65a4cdc01040810cbdb51d5efeb7dc778b/stroyprombeton/tests/tests_views.py#L302-L303

The puzzle was created by duker33 on 05-Jul-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
prod series fill good now. So, it's about dev env. Fixtures or smth

**Comment by duker33** [comment]
prod met the bug too. But the local env is more looks interesting, see the screen
![image](https://user-images.githubusercontent.com/3526796/60967014-44ccd180-a322-11e9-90e1-2906a9b30ebf.png)
