### ISSUE TITLE
Post-sections header markup fixes

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#736]
The logo has been cutten because of two many menu items.
Search form markup has been hurt too.

![image](https://user-images.githubusercontent.com/3526796/60867319-3653bc80-a233-11e9-826c-81dd01f4c015.png)

**Comment by duker33** [comment]
Removed example categories. I'll add some examples at another task

![image](https://user-images.githubusercontent.com/3526796/60869518-ce53a500-a237-11e9-9428-e33c225eee0a.png)

**Comment by duker33** [comment]
now example categories look like this
![image](https://user-images.githubusercontent.com/3526796/60869884-7ec1a900-a238-11e9-9e23-f04beb36b533.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#740](https://github.com/fidals/stroyprombeton/issues/740) is still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#740](https://github.com/fidals/stroyprombeton/issues/740), [#741](https://github.com/fidals/stroyprombeton/issues/741), [#742](https://github.com/fidals/stroyprombeton/issues/742) are still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#741](https://github.com/fidals/stroyprombeton/issues/741), [#742](https://github.com/fidals/stroyprombeton/issues/742), [#749](https://github.com/fidals/stroyprombeton/issues/749) are still not solved; solved: [#740](https://github.com/fidals/stroyprombeton/issues/740).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#749](https://github.com/fidals/stroyprombeton/issues/749), [#759](https://github.com/fidals/stroyprombeton/issues/759), [#760](https://github.com/fidals/stroyprombeton/issues/760), [#761](https://github.com/fidals/stroyprombeton/issues/761), [#762](https://github.com/fidals/stroyprombeton/issues/762), [#763](https://github.com/fidals/stroyprombeton/issues/763), [#764](https://github.com/fidals/stroyprombeton/issues/764) are still not solved; solved: [#740](https://github.com/fidals/stroyprombeton/issues/740), [#741](https://github.com/fidals/stroyprombeton/issues/741), [#742](https://github.com/fidals/stroyprombeton/issues/742).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#536](https://github.com/fidals/stroyprombeton/issues/536), [#759](https://github.com/fidals/stroyprombeton/issues/759), [#760](https://github.com/fidals/stroyprombeton/issues/760), [#761](https://github.com/fidals/stroyprombeton/issues/761), [#762](https://github.com/fidals/stroyprombeton/issues/762), [#763](https://github.com/fidals/stroyprombeton/issues/763), [#764](https://github.com/fidals/stroyprombeton/issues/764) are still not solved; solved: [#740](https://github.com/fidals/stroyprombeton/issues/740), [#741](https://github.com/fidals/stroyprombeton/issues/741), [#742](https://github.com/fidals/stroyprombeton/issues/742), [#749](https://github.com/fidals/stroyprombeton/issues/749).
