### ISSUE TITLE
parse_stalbeton.py:86-88: Try to use stalbeton...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#742]
The puzzle `736-8fdc8f25` from #736 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/f7e5cfc60349563bb851b7329b2b635d2dfc9f6f/stroyprombeton/management/commands/parse_stalbeton.py#L86-L88

The puzzle was created by duker33 on 10-Jul-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
sitemap seemed a perfect idea because it contains all urls all over the site. Despite that it's not required, because we should parse every catalog page to fetch relations and page's seo metadata
