### ISSUE TITLE
Fix pdf price generation

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#744]
It should render options list with tags containing dimensions.

![bad_price](https://user-images.githubusercontent.com/3526796/60966111-2c5bb780-a320-11e9-8e2e-836ac6e3e99c.png)

![good_structure](https://user-images.githubusercontent.com/3526796/60966154-472e2c00-a320-11e9-8147-d7eee16b3e13.png)

**Comment by artemiy312** [comment]
I am going to little bit rework context classes here

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#755](https://github.com/fidals/stroyprombeton/issues/755), [#756](https://github.com/fidals/stroyprombeton/issues/756) are still not solved.
