### ISSUE TITLE
Bad dimension units at tags content

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#746]
It should be "Длина 8000 мм", but not "Длина 8000 м".
Explore if every value "длина/ширина/высота" dimension should have "мм" instead of "м" units.
If should change it with script. If not, the task will wait for stalbeton catalog taking (#738 with all subtasks)

![image](https://user-images.githubusercontent.com/3526796/60966593-4649ca00-a321-11e9-8ad8-7b39b8a60013.png)

**Comment by duker33** [comment]
take additional `30 mins` for units change, if you'll change them

**Comment by artemiy312** [comment]
I need to explore Длина, Высота, Ширина, Внешний диаметр, Внутренний диаметр tag groups

**Comment by artemiy312** [comment]
We have tags with м from 0 to 26000.

I believe we should move every tag with м >20+2 for length, >4 for height, >2.55 for width and inner/outer diameter to мм units, because it is dimensions restriction of cargo for transportation. [23.5 paragraph](https://auto.mail.ru/info/pdd/23/)

**Comment by duker33** [comment]
@artemiy312 , y, every GBI presented with catalog should obey standart dimensions limits. You've done a great job finding `23.5 paragraph`, thx!
Let's take your's formula to fix dimensions

**Comment by artemiy312** [comment]
@duker33 I'll create separate issue to fix it

**Comment by duker33** [comment]
@artemiy312 , if you'll implement the new task for your own, you can just increase time here instead of creating it. Your script will not append our codebase, so it's not necessary to create separated task
